CREATE TABLE [Selections].[__ROCShopperSegment_PreSelection_ALS_Old_Archived] (
    [ID]                         INT           IDENTITY (1, 1) NOT NULL,
    [EmailDate]                  DATE          NULL,
    [PartnerID]                  CHAR (4)      NULL,
    [StartDate]                  DATE          NULL,
    [EndDate]                    DATE          NULL,
    [MarketableByEmail]          VARCHAR (10)  NULL,
    [PaymentMethodsAvailable]    VARCHAR (10)  NULL,
    [OfferID]                    VARCHAR (40)  NULL,
    [Throttling]                 VARCHAR (200) NULL,
    [ClientServicesRef]          VARCHAR (10)  NULL,
    [OutputTableName]            VARCHAR (100) NULL,
    [CampaignName]               VARCHAR (250) NULL,
    [SelectionDate]              VARCHAR (11)  NULL,
    [DeDupeAgainstCampaigns]     VARCHAR (50)  NULL,
    [NotIn_TableName1]           VARCHAR (100) NULL,
    [NotIn_TableName2]           VARCHAR (100) NULL,
    [NotIn_TableName3]           VARCHAR (100) NULL,
    [NotIn_TableName4]           VARCHAR (100) NULL,
    [MustBeIn_TableName1]        VARCHAR (100) NULL,
    [MustBeIn_TableName2]        VARCHAR (100) NULL,
    [MustBeIn_TableName3]        VARCHAR (100) NULL,
    [MustBeIn_TableName4]        VARCHAR (100) NULL,
    [Gender]                     CHAR (1)      NULL,
    [AgeRange]                   VARCHAR (7)   NULL,
    [CampaignID_Include]         CHAR (3)      NULL,
    [CampaignID_Exclude]         CHAR (3)      NULL,
    [DriveTimeMins]              CHAR (3)      NULL,
    [LiveNearAnyStore]           BIT           NULL,
    [OutletSector]               CHAR (6)      NULL,
    [SocialClass]                VARCHAR (5)   NULL,
    [SelectedInAnotherCampaign]  VARCHAR (250) NULL,
    [CampaignTypeID]             CHAR (1)      NULL,
    [CustomerBaseOfferDate]      DATE          NULL,
    [ReadyToRun]                 BIT           NULL,
    [SelectionRun]               BIT           NULL,
    [RandomThrottle]             BIT           NULL,
    [PriorityFlag]               INT           NULL,
    [NewCampaign]                BIT           NULL,
    [PredictedCardholderVolumes] VARCHAR (50)  NULL,
    [BriefLocation]              VARCHAR (250) NULL,
    [sProcPreSelection]          VARCHAR (150) NULL,
    [CampaignCycleLength]        INT           NULL,
    [BespokeCampaign]            BIT           NULL,
    [FreqStretch_TransCount]     INT           NULL,
    [ControlGroupPercentage]     INT           NULL
);

