CREATE TABLE [Selections].[CampaignSetup_BriefInsert_OfferDetails_Import] (
    [ID]       INT            IDENTITY (1, 1) NOT NULL,
    [ColumnA]  NVARCHAR (255) NULL,
    [ColumnB]  NVARCHAR (255) NULL,
    [ColumnC]  NVARCHAR (255) NULL,
    [ColumnD]  NVARCHAR (255) NULL,
    [ColumnE]  NVARCHAR (255) NULL,
    [ColumnF]  NVARCHAR (255) NULL,
    [ColumnG]  NVARCHAR (255) NULL,
    [ColumnH]  NVARCHAR (255) NULL,
    [ColumnI]  NVARCHAR (255) NULL,
    [ColumnJ]  NVARCHAR (255) NULL,
    [ColumnK]  NVARCHAR (255) NULL,
    [ColumnL]  NVARCHAR (255) NULL,
    [ColumnM]  NVARCHAR (255) NULL,
    [ColumnN]  NVARCHAR (255) NULL,
    [ColumnO]  NVARCHAR (255) NULL,
    [ColumnP]  NVARCHAR (255) NULL,
    [ColumnQ]  NVARCHAR (255) NULL,
    [ColumnR]  NVARCHAR (255) NULL,
    [ColumnS]  NVARCHAR (255) NULL,
    [ColumnT]  NVARCHAR (255) NULL,
    [ColumnU]  NVARCHAR (255) NULL,
    [ColumnV]  NVARCHAR (255) NULL,
    [ColumnW]  NVARCHAR (255) NULL,
    [ColumnX]  NVARCHAR (255) NULL,
    [ColumnY]  NVARCHAR (255) NULL,
    [ColumnZ]  NVARCHAR (255) NULL,
    [ColumnAA] NVARCHAR (255) NULL,
    [ColumnAB] NVARCHAR (255) NULL,
    [ColumnAC] NVARCHAR (255) NULL,
    [ColumnAD] NVARCHAR (255) NULL,
    [ColumnAE] NVARCHAR (255) NULL
);

