CREATE TABLE [Selections].[CampaignSetup_CampaignCountsAndSetup] (
    [EmailDate]                    VARCHAR (10)   NULL,
    [CycleStart_Email]             VARCHAR (10)   NULL,
    [PartnerID]                    INT            NULL,
    [PartnerName]                  VARCHAR (100)  NULL,
    [ClientServicesRef]            VARCHAR (40)   NULL,
    [CycleStart_Campaign]          VARCHAR (10)   NULL,
    [OutputTableName]              VARCHAR (80)   NULL,
    [IronOfferID]                  INT            NULL,
    [IronOfferName]                NVARCHAR (200) NULL,
    [Throttling]                   INT            NULL,
    [NewCampaign]                  INT            NULL,
    [OPE]                          VARCHAR (7)    NOT NULL,
    [Campaign_HTM]                 VARCHAR (15)   NOT NULL,
    [PreSelection_ALS]             VARCHAR (19)   NOT NULL,
    [Selections]                   VARCHAR (20)   NULL,
    [NomTableNames]                VARCHAR (12)   NOT NULL,
    [NomTableNamesCount]           INT            NULL,
    [OfferProcessLog]              VARCHAR (17)   NULL,
    [MissingInformation]           VARCHAR (3)    NOT NULL,
    [CountFromIOMCurrent]          INT            NULL,
    [CountFromSandbox]             INT            NULL,
    [CountFromOfferMemberAddition] INT            NULL,
    [CountFromIOMUpcoming]         INT            NULL,
    [PredictedCardholderVolumes]   INT            NULL
);

