CREATE TABLE [Selections].[DataVal_EarnOFfer] (
    [FanID_Profile]           INT           NULL,
    [ClubID]                  INT           NULL,
    [EmailAddress]            NVARCHAR (50) NULL,
    [CashbackAvailable]       FLOAT (53)    NULL,
    [CashbackPending]         FLOAT (53)    NULL,
    [LifetimeValue]           FLOAT (53)    NULL,
    [IsDebit]                 NVARCHAR (50) NULL,
    [IsCredit]                NVARCHAR (50) NULL,
    [LoyaltyAccount]          NVARCHAR (50) NULL,
    [CustomerSegment]         NVARCHAR (50) NULL,
    [CreationMoment_Profile]  DATETIME2 (7) NULL,
    [UpdateMoment_Profile]    DATETIME2 (7) NULL,
    [FanID_Offer]             INT           NULL,
    [EmailSendID]             INT           NULL,
    [EmailSendName]           NVARCHAR (1)  NULL,
    [EarnOfferID_Hero]        INT           NULL,
    [EarnOfferStartDate_Hero] DATETIME2 (7) NULL,
    [EarnOfferEndDate_Hero]   DATETIME2 (7) NULL,
    [EarnOfferID_1]           INT           NULL,
    [EarnOfferStartDate_1]    DATETIME2 (7) NULL,
    [EarnOfferEndDate_1]      DATETIME2 (7) NULL,
    [EarnOfferID_2]           INT           NULL,
    [EarnOfferStartDate_2]    DATETIME2 (7) NULL,
    [EarnOfferEndDate_2]      DATETIME2 (7) NULL,
    [EarnOfferID_3]           INT           NULL,
    [EarnOfferStartDate_3]    DATETIME2 (7) NULL,
    [EarnOfferEndDate_3]      DATETIME2 (7) NULL,
    [EarnOfferID_4]           INT           NULL,
    [EarnOfferStartDate_4]    DATETIME2 (7) NULL,
    [EarnOfferEndDate_4]      DATETIME2 (7) NULL,
    [EarnOfferID_5]           INT           NULL,
    [EarnOfferStartDate_5]    DATETIME2 (7) NULL,
    [EarnOfferEndDate_5]      DATETIME2 (7) NULL,
    [EarnOfferID_6]           INT           NULL,
    [EarnOfferStartDate_6]    DATETIME2 (7) NULL,
    [EarnOfferEndDate_6]      DATETIME2 (7) NULL,
    [CreationMoment_Offer]    DATETIME2 (7) NULL,
    [UpdateMoment_Offer]      DATETIME2 (7) NULL
);

