CREATE TABLE [Selections].[ROCShopperSegment_CampaignSetup_SelectionTable] (
    [Publisher]                    VARCHAR (50)  NULL,
    [PartnerID]                    VARCHAR (50)  NULL,
    [PartnerName]                  VARCHAR (100) NULL,
    [ClientServicesRef]            VARCHAR (50)  NULL,
    [CampaignName]                 VARCHAR (100) NULL,
    [CampaignStart]                DATE          NULL,
    [CampaignEnd]                  DATE          NULL,
    [CycleNumber]                  VARCHAR (50)  NULL,
    [CycleStart]                   VARCHAR (50)  NULL,
    [CycleEnd]                     VARCHAR (50)  NULL,
    [ShopperSegment]               VARCHAR (50)  NULL,
    [IronOfferID]                  VARCHAR (50)  NULL,
    [OfferRate]                    VARCHAR (50)  NULL,
    [SpendStretchAmount]           VARCHAR (50)  NULL,
    [AboveSpendStretchRate]        VARCHAR (50)  NULL,
    [OfferBillingRate]             VARCHAR (50)  NULL,
    [AboveSpendStretchBillingRate] VARCHAR (50)  NULL,
    [Gender]                       VARCHAR (50)  NULL,
    [AgeGroupMin]                  VARCHAR (50)  NULL,
    [AgeGroupMax]                  VARCHAR (50)  NULL,
    [DriveTime]                    VARCHAR (50)  NULL,
    [SocialClassLowest]            VARCHAR (50)  NULL,
    [SocialClassHighest]           VARCHAR (50)  NULL,
    [MarketableByEmail]            VARCHAR (50)  NULL,
    [Throttle]                     INT           NOT NULL,
    [RandomThrottle]               INT           NOT NULL,
    [CompetitorType]               VARCHAR (50)  NULL,
    [CompetitorCampaignID]         VARCHAR (50)  NULL,
    [DedupeAgainstCampaigns]       VARCHAR (50)  NULL,
    [SelectedInAnotherCampaign]    VARCHAR (50)  NULL,
    [CustomerBaseDate]             VARCHAR (50)  NULL,
    [sProcPreSelection]            VARCHAR (100) NULL,
    [PredictedCardholderVolumes]   VARCHAR (50)  NULL,
    [ActualCardholderVolumes]      VARCHAR (50)  NULL,
    [OutputTableName]              VARCHAR (100) NULL,
    [NotIn_TableName1]             VARCHAR (100) NULL,
    [NotIn_TableName2]             VARCHAR (100) NULL,
    [NotIn_TableName3]             VARCHAR (100) NULL,
    [NotIn_TableName4]             VARCHAR (100) NULL,
    [Must_BeInTableName1]          VARCHAR (100) NULL,
    [Must_BeInTableName2]          VARCHAR (100) NULL,
    [Must_BeInTableName3]          VARCHAR (100) NULL,
    [Must_BeInTableName4]          VARCHAR (100) NULL,
    [BriefFilePath]                VARCHAR (250) NULL,
    [PriorityFlag]                 VARCHAR (50)  NULL,
    [PriorityFlag_Ranked]          BIGINT        NULL,
    [NewCampaign]                  INT           NOT NULL,
    [ReadyToRun]                   VARCHAR (50)  NULL,
    [SelectionRun]                 VARCHAR (50)  NULL
);

