CREATE TABLE [Selections].[ROCShopperSegment_BriefInput] (
    [Publisher]                    VARCHAR (50) NULL,
    [ClientServicesRef]            VARCHAR (50) NULL,
    [CampaignStart]                DATE         NULL,
    [CampaignEnd]                  DATE         NULL,
    [CycleNumber]                  VARCHAR (50) NULL,
    [CycleStart]                   VARCHAR (50) NULL,
    [CycleEnd]                     VARCHAR (50) NULL,
    [ShopperSegment]               VARCHAR (50) NULL,
    [SelectionTopXPercent]         VARCHAR (50) NULL,
    [Gender]                       VARCHAR (50) NULL,
    [AgeGroupMin]                  VARCHAR (50) NULL,
    [AgeGroupMax]                  VARCHAR (50) NULL,
    [DriveTime]                    VARCHAR (50) NULL,
    [SocialClassLowest]            VARCHAR (50) NULL,
    [SocialClassHighest]           VARCHAR (50) NULL,
    [MarketableByEmail]            VARCHAR (50) NULL,
    [OfferRate]                    VARCHAR (50) NULL,
    [SpendStretchAmount]           VARCHAR (50) NULL,
    [AboveSpendStretchRate]        VARCHAR (50) NULL,
    [IronOfferID]                  VARCHAR (50) NULL,
    [RandomThrottle]               VARCHAR (50) NULL,
    [OfferBillingRate]             VARCHAR (50) NULL,
    [AboveSpendStretchBillingRate] VARCHAR (50) NULL,
    [PredictedCardholderVolumes]   VARCHAR (50) NULL,
    [ActualCardholderVolumes]      VARCHAR (50) NULL,
    [OfferToSelectFromBrief]       VARCHAR (50) NULL
);

