CREATE TABLE [SmartEmail].[DailyData_NoWayToEarn] (
    [Email]                      NVARCHAR (100) NOT NULL,
    [FanID]                      INT            NOT NULL,
    [ClubID]                     INT            NOT NULL,
    [ClubName]                   VARCHAR (1)    NOT NULL,
    [FirstName]                  NVARCHAR (50)  NOT NULL,
    [Lastname]                   NVARCHAR (50)  NOT NULL,
    [dob]                        DATE           NULL,
    [Sex]                        TINYINT        NOT NULL,
    [FromAddress]                VARCHAR (1)    NOT NULL,
    [FromName]                   VARCHAR (1)    NOT NULL,
    [ClubCashAvailable]          SMALLMONEY     NOT NULL,
    [ClubCashPending]            SMALLMONEY     NULL,
    [PartialPostCode]            NVARCHAR (3)   NULL,
    [Title]                      NVARCHAR (20)  NULL,
    [AgreedTcsDate]              DATETIME       NULL,
    [WelcomeEmailCode]           VARCHAR (10)   NULL,
    [IsDebit]                    BIT            NULL,
    [IsCredit]                   BIT            NULL,
    [Nominee]                    INT            NULL,
    [RBSNomineeChange]           INT            NULL,
    [LoyaltyAccount]             BIT            NULL,
    [IsLoyalty]                  BIT            NULL,
    [FirstEarnDate]              DATE           NULL,
    [FirstEarnType]              VARCHAR (100)  NULL,
    [Reached5GBP]                DATE           NULL,
    [Homemover]                  BIT            NULL,
    [Day60AccountName]           VARCHAR (30)   NULL,
    [Day120AccountName]          VARCHAR (30)   NULL,
    [JointAccount]               BIT            NULL,
    [FulfillmentTypeID]          INT            NULL,
    [CaffeNeroBirthdayCode]      VARCHAR (40)   NULL,
    [ExpiryDate]                 DATE           NULL,
    [LvTotalEarning]             SMALLMONEY     NULL,
    [LVCurrentMonthEarning]      INT            NOT NULL,
    [LvMonth1Earning]            INT            NOT NULL,
    [LvMonth2Earning]            INT            NOT NULL,
    [LvMonth3Earning]            INT            NOT NULL,
    [LvMonth4Earning]            INT            NOT NULL,
    [LvMonth5Earning]            INT            NOT NULL,
    [LvMonth6Earning]            INT            NOT NULL,
    [LvMonth7Earning]            INT            NOT NULL,
    [LvMonth8Earning]            INT            NOT NULL,
    [LvMonth9Earning]            INT            NOT NULL,
    [LvMonth10Earning]           INT            NOT NULL,
    [LvMonth11Earning]           INT            NOT NULL,
    [CPOSEarning]                SMALLMONEY     NOT NULL,
    [DPOSEarning]                SMALLMONEY     NOT NULL,
    [DDEarning]                  SMALLMONEY     NOT NULL,
    [OtherEarning]               SMALLMONEY     NOT NULL,
    [CurrentAnniversaryEarning]  SMALLMONEY     NOT NULL,
    [PreviousAnniversaryEarning] SMALLMONEY     NOT NULL,
    [LvEAYBEarning]              INT            NOT NULL,
    [Marketable]                 INT            NOT NULL,
    [GroupDesc]                  VARCHAR (34)   NULL
);

