CREATE TABLE [Rory].[EarnOffer_20220310] (
    [FanID]                   BIGINT      NULL,
    [EmailSendID]             INT         NULL,
    [EmailSendName]           VARCHAR (1) NOT NULL,
    [EarnOfferID_Hero]        INT         NULL,
    [EarnOfferID_1]           INT         NULL,
    [EarnOfferID_2]           INT         NULL,
    [EarnOfferID_3]           INT         NULL,
    [EarnOfferID_4]           INT         NULL,
    [EarnOfferID_5]           INT         NULL,
    [EarnOfferID_6]           INT         NULL,
    [EarnOfferID_7]           INT         NULL,
    [EarnOfferID_8]           INT         NULL,
    [EarnOfferStartDate_Hero] DATE        NULL,
    [EarnOfferStartDate_1]    DATE        NULL,
    [EarnOfferStartDate_2]    DATE        NULL,
    [EarnOfferStartDate_3]    DATE        NULL,
    [EarnOfferStartDate_4]    DATE        NULL,
    [EarnOfferStartDate_5]    DATE        NULL,
    [EarnOfferStartDate_6]    DATE        NULL,
    [EarnOfferStartDate_7]    DATE        NULL,
    [EarnOfferStartDate_8]    DATE        NULL,
    [EarnOfferEndDate_Hero]   DATE        NULL,
    [EarnOfferEndDate_1]      DATE        NULL,
    [EarnOfferEndDate_2]      DATE        NULL,
    [EarnOfferEndDate_3]      DATE        NULL,
    [EarnOfferEndDate_4]      DATE        NULL,
    [EarnOfferEndDate_5]      DATE        NULL,
    [EarnOfferEndDate_6]      DATE        NULL,
    [EarnOfferEndDate_7]      DATE        NULL,
    [EarnOfferEndDate_8]      DATE        NULL
);

