CREATE TABLE [Rory].[SchemeTrans_Dim_MisingFromRewardBI] (
    [ID]                  INT          IDENTITY (1, 1) NOT NULL,
    [SourceID]            INT          NOT NULL,
    [SourceTableID]       INT          NOT NULL,
    [PublisherID]         INT          NOT NULL,
    [SubPublisherID]      TINYINT      NOT NULL,
    [NotRewardManaged]    BIT          NOT NULL,
    [RetailerID]          INT          NOT NULL,
    [PartnerID]           INT          NOT NULL,
    [OfferID]             INT          NULL,
    [IronOfferID]         INT          NULL,
    [OfferPercentage]     FLOAT (53)   NOT NULL,
    [CommissionRate]      FLOAT (53)   NOT NULL,
    [OutletID]            INT          NOT NULL,
    [FanID]               INT          NOT NULL,
    [PanID]               INT          NULL,
    [Spend]               MONEY        NOT NULL,
    [RetailerCashback]    MONEY        NOT NULL,
    [Investment]          MONEY        NOT NULL,
    [PublisherCommission] MONEY        NOT NULL,
    [RewardCommission]    SMALLMONEY   NOT NULL,
    [VATCommission]       MONEY        NOT NULL,
    [GrossCommission]     MONEY        NOT NULL,
    [TranDate]            DATE         NOT NULL,
    [TranFixDate]         DATE         NULL,
    [TranTime]            TIME (7)     NOT NULL,
    [IsNegative]          BIT          NOT NULL,
    [IsOnline]            BIT          NOT NULL,
    [IsSpendStretch]      BIT          NULL,
    [SpendStretchAmount]  MONEY        NULL,
    [IsRetailMonthly]     BIT          NOT NULL,
    [IsRetailerReport]    BIT          NOT NULL,
    [AddedDate]           DATE         NOT NULL,
    [MaskedCardNumber]    VARCHAR (19) NULL
);

