CREATE TABLE [Rory].[SchemeTrans_Dim_New] (
    [SourceID]            INT             NOT NULL,
    [SourceTableID]       INT             NOT NULL,
    [PublisherID]         INT             NOT NULL,
    [SubPublisherID]      INT             NOT NULL,
    [NotRewardManaged]    INT             NOT NULL,
    [RetailerID]          INT             NULL,
    [PartnerID]           INT             NOT NULL,
    [OfferID]             INT             NOT NULL,
    [IronOfferID]         INT             NULL,
    [OfferPercentage]     DECIMAL (32, 4) NOT NULL,
    [CommissionRate]      DECIMAL (32, 4) NOT NULL,
    [OutletID]            INT             NULL,
    [FanID]               INT             NOT NULL,
    [PanID]               INT             NULL,
    [MaskedCardNumber]    VARCHAR (19)    NULL,
    [Spend]               DECIMAL (32, 2) NULL,
    [RetailerCashback]    DECIMAL (32, 2) NULL,
    [Investment]          DECIMAL (32, 2) NULL,
    [PublisherCommission] DECIMAL (32, 2) NULL,
    [RewardCommission]    DECIMAL (32, 2) NULL,
    [VATCommission]       DECIMAL (32, 2) NULL,
    [GrossCommission]     DECIMAL (32, 2) NULL,
    [TranDate]            DATETIME        NOT NULL,
    [TranFixDate]         DATETIME        NULL,
    [TranTime]            TIME (7)        NULL,
    [IsNegative]          INT             NOT NULL,
    [IsOnline]            INT             NOT NULL,
    [IsSpendStretch]      INT             NULL,
    [SpendStretchAmount]  DECIMAL (32, 2) NULL,
    [IsRetailMonthly]     INT             NOT NULL,
    [IsRetailerReport]    INT             NOT NULL,
    [AddedDate]           DATETIME        NOT NULL
);

