

CREATE PROC [WHB].[__Visa_LandingIronOffer_Load]
AS
INSERT INTO [WH_AllPublishers].[Inbound].[Visa_IronOffer]([IronOfferID]
      ,[IronOfferName]
      ,[HydraOfferID]
      ,[StartDate]
      ,[EndDate]
      ,[PartnerID]
      ,[IsAboveTheLine]
      ,[AutoAddToNewRegistrants]
      ,[IsDefaultCollateral]
      ,[IsSignedOff]
      ,[AreEligibleMembersCommitted]
      ,[AreControlMembersCommitted]
      ,[IsTriggerOffer]
      ,[Continuation]
      ,[TopCashBackRate]
      ,[AboveBase]
      ,[Clubs]
      ,[CampaignType]
      ,[SegmentName]
      ,[ClubID])
SELECT
	[IronOfferID]
      ,[IronOfferName]
      ,[HydraOfferID]
      ,[StartDate]
      ,[EndDate]
      ,[PartnerID]
      ,[IsAboveTheLine]
      ,[AutoAddToNewRegistrants]
      ,[IsDefaultCollateral]
      ,[IsSignedOff]
      ,[AreEligibleMembersCommitted]
      ,[AreControlMembersCommitted]
      ,[IsTriggerOffer]
      ,[Continuation]
      ,[TopCashBackRate]
      ,[AboveBase]
      ,[Clubs]
      ,[CampaignType]
      ,[SegmentName]
      ,[ClubID]
  FROM [WH_Visa].[Derived].[IronOffer]
WHERE [HydraOfferID] IS NOT NULL
