CREATE TABLE [WHB].[Missing_Earnings] (
    [EarningID]                 INT           IDENTITY (1, 1) NOT NULL,
    [ConsumerID]                INT           NOT NULL,
    [PartnerID]                 INT           NULL,
    [RetailerID]                INT           NULL,
    [OutletID]                  INT           NULL,
    [IsOnline]                  BIT           NULL,
    [CardHolderPresentData]     CHAR (1)      NULL,
    [TransactionAmount]         SMALLMONEY    NOT NULL,
    [ExtremeValueFlag]          BIT           NULL,
    [TransactionDate]           DATE          NULL,
    [AffiliateCommissionAmount] SMALLMONEY    NULL,
    [CommissionChargable]       MONEY         NULL,
    [CashbackEarned]            MONEY         NULL,
    [OfferID]                   INT           NULL,
    [ActivationDays]            INT           NULL,
    [AboveBase]                 INT           NULL,
    [PaymentMethodID]           TINYINT       NULL,
    [SourceID]                  VARCHAR (36)  NOT NULL,
    [SourceSystemID]            INT           NOT NULL,
    [SourceTypeID]              INT           NOT NULL,
    [SourceAddedDate]           DATE          NULL,
    [CreatedDateTime]           DATETIME2 (7) NOT NULL
);

