CREATE TABLE [Email].[OfferSlotData] (
    [FanID]               INT  NOT NULL,
    [LionSendID]          INT  NOT NULL,
    [OfferID_Hero]        INT  NOT NULL,
    [OfferID_1]           INT  NOT NULL,
    [OfferID_2]           INT  NOT NULL,
    [OfferID_3]           INT  NOT NULL,
    [OfferID_4]           INT  NOT NULL,
    [OfferID_5]           INT  NOT NULL,
    [OfferID_6]           INT  NOT NULL,
    [OfferID_7]           INT  NOT NULL,
    [OfferID_8]           INT  NOT NULL,
    [OfferStartDate_Hero] DATE NULL,
    [OfferStartDate_1]    DATE NULL,
    [OfferStartDate_2]    DATE NULL,
    [OfferStartDate_3]    DATE NULL,
    [OfferStartDate_4]    DATE NULL,
    [OfferStartDate_5]    DATE NULL,
    [OfferStartDate_6]    DATE NULL,
    [OfferStartDate_7]    DATE NULL,
    [OfferStartDate_8]    DATE NULL,
    [OfferEndDate_Hero]   DATE NULL,
    [OfferEndDate_1]      DATE NULL,
    [OfferEndDate_2]      DATE NULL,
    [OfferEndDate_3]      DATE NULL,
    [OfferEndDate_4]      DATE NULL,
    [OfferEndDate_5]      DATE NULL,
    [OfferEndDate_6]      DATE NULL,
    [OfferEndDate_7]      DATE NULL,
    [OfferEndDate_8]      DATE NULL,
    PRIMARY KEY CLUSTERED ([FanID] ASC)
);

