CREATE PROCEDURE [FIFO].[_Build]
AS
BEGIN

	TRUNCATE TABLE FIFO.Reductions
	TRUNCATE TABLE FIFO.Earnings
	TRUNCATE TABLE FIFO.ReductionIntervals
	TRUNCATE TABLE FIFO.ReductionAllocations

	EXEC FIFO._Build_Resume

END