CREATE TABLE [Ewan].[EngagementMetrics_byCycle] (
    [CycleID]                INT  NULL,
    [CycleStartDate]         DATE NULL,
    [CycleEndDate]           DATE NULL,
    [ActiveCustomers]        INT  NULL,
    [Activations]            INT  NULL,
    [Deactivations]          INT  NULL,
    [EmailsSent]             INT  NULL,
    [EmailsOpened]           INT  NULL,
    [EmailOpenRate]          INT  NULL,
    [WebLogins]              INT  NULL,
    [OfferPageViews]         INT  NULL,
    [AvgTimeSpentonSite]     INT  NULL,
    [NrCashRedemptions]      INT  NULL,
    [SumCashRedemptions]     INT  NULL,
    [NrTURedemptions]        INT  NULL,
    [SumTURedemptions]       INT  NULL,
    [NrCharityRedemptions]   INT  NULL,
    [SumCharityRedemptions]  INT  NULL,
    [TradeUpProportion]      INT  NULL,
    [MerchantCashback]       INT  NULL,
    [Count_Gold]             INT  NULL,
    [Count_Silver]           INT  NULL,
    [Count_Bronze]           INT  NULL,
    [Count_Blue]             INT  NULL,
    [MF_Gold]                INT  NULL,
    [MF_Silver]              INT  NULL,
    [MF_Bronze]              INT  NULL,
    [MF_Blue]                INT  NULL,
    [RBS_Cashback]           INT  NULL,
    [TotalCashbackAvailable] INT  NULL,
    [RetailersLive]          INT  NULL
);

