CREATE LOGIN [CRTImport]
    WITH PASSWORD = N'olq:shn&3Gkynzc{goq8r,{dmsFT7_&#$!~<|{crqwnffysq', SID = 0x4CD3B3DDF48D9E42B45FE90C978DE595, DEFAULT_DATABASE = [Archive_Light], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

