CREATE LOGIN [Vernon]
    WITH PASSWORD = N'sacnnk5skgl fQy`?Nj1dldrmsFT7_&#$!~<6r~rwSgan|oh', SID = 0xA7FC05F8E37ACB42AAAA8F201E2FF369, DEFAULT_DATABASE = [Sandbox], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

