CREATE LOGIN [VitaliiV]
    WITH PASSWORD = N'wouqdzsb`blP|mu{styqtrrumsFT7_&#$!~<bfj}9b6at|7g', SID = 0x2D08581BA4AA6F4EB3AC7CC76FE6085B, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

