CREATE LOGIN [CRTImport]
    WITH PASSWORD = N'~kN&d5td|k|m$6o2tjvj{wDwmsFT7_&#$!~<cprrF}ijjgjq', SID = 0x4CD3B3DDF48D9E42B45FE90C978DE595, DEFAULT_DATABASE = [Archive_Light], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

