CREATE LOGIN [JoanneK]
    WITH PASSWORD = N'ijufz9iFeabsdBscn6axg>x^msFT7_&#$!~<lfDxzrhpxkib', SID = 0xF20985CCED049742B4FF07EA6CA17EF6, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

