CREATE TABLE [RBSMIPortal].[SchemeCashback] (
    [ID]                     INT           NOT NULL,
    [SchemeTransID]          INT           NULL,
    [FanID]                  INT           NOT NULL,
    [Spend]                  MONEY         NOT NULL,
    [Cashback]               MONEY         NOT NULL,
    [AddedDate]              DATE          NOT NULL,
    [TranDate]               DATE          NOT NULL,
    [EligibleDate]           DATE          NOT NULL,
    [CashbackSourceID]       SMALLINT      NOT NULL,
    [CashbackSourceName]     VARCHAR (50)  NOT NULL,
    [OfferAboveBase]         BIT           NULL,
    [AddedWeekID]            SMALLINT      NULL,
    [AddedMonthID]           SMALLINT      NULL,
    [RBSFunded]              TINYINT       NOT NULL,
    [BankID]                 TINYINT       NULL,
    [CashbackAwardCategory]  VARCHAR (50)  NOT NULL,
    [PaymentMethodID]        SMALLINT      NOT NULL,
    [PaymentMethod]          VARCHAR (50)  NOT NULL,
    [FundingType]            VARCHAR (50)  NOT NULL,
    [CashbackAwardTypeID]    TINYINT       NULL,
    [PartnerID]              INT           NOT NULL,
    [PartnerName]            VARCHAR (100) NOT NULL,
    [OfferName]              VARCHAR (200) NOT NULL,
    [SchemeMembershipTypeID] TINYINT       NOT NULL,
    [IsVSegment]             BIT           NOT NULL,
    CONSTRAINT [PK_RBSMIPortal_SchemeCashback] PRIMARY KEY CLUSTERED ([ID] ASC)
);

