

CREATE Procedure [Staging].[ExcelQuery_ROCEFT_LIVE_FullRefresh_Exec]
as
BEGIN 

	IF DATENAME(DW,GETDATE()) = 'Sunday' 
	BEGIN 

		EXEC msdb.dbo.sp_send_dbmail 
				@profile_name = 'Administrator', 
				@recipients='diprocesscheckers@rewardinsight.com; Insight@rewardinsight.com',
				@subject = 'ROC Tool Full Refresh - Started',
				@body='This is an autogenerated message to inform you that the ROC Tool Full Refresh has been initiated. You will be informed upon completion.',
				@body_format = 'TEXT', 
		   --   @importance = 'HIGH', 
				@exclude_query_output = 1
	
		EXEC [ExcelQuery].[ROCEFT_LIVE_FullRefresh]

		EXEC msdb.dbo.sp_send_dbmail 
				@profile_name = 'Administrator', 
				@recipients='diprocesscheckers@rewardinsight.com; Insight@rewardinsight.com',
				@subject = 'ROC Tool Full Refresh - Completed',
				@body='This is an autogenerated message to inform you that the ROC Tool Full Refresh has completed.',
				@body_format = 'TEXT', 
			 -- @importance = 'HIGH', 
				@exclude_query_output = 1

	END --if

END