CREATE TABLE [Derived].[LoginInfo2] (
    [LoginInfoID]         INT            IDENTITY (1, 1) NOT NULL,
    [AgentString]         VARCHAR (1000) NOT NULL,
    [AgentType]           VARCHAR (30)   NULL,
    [AgentBrand]          VARCHAR (30)   NULL,
    [AgentName]           VARCHAR (30)   NULL,
    [AgentUrl]            VARCHAR (1000) NULL,
    [OsName]              VARCHAR (30)   NULL,
    [OsCode]              VARCHAR (30)   NULL,
    [OsUrl]               VARCHAR (1000) NULL,
    [OsFamily]            VARCHAR (30)   NULL,
    [OsFamilycode]        VARCHAR (30)   NULL,
    [OsFamilyvendor]      VARCHAR (30)   NULL,
    [OsIcon]              VARCHAR (500)  NULL,
    [OsIconLarge]         VARCHAR (500)  NULL,
    [isMobile]            BIT            NULL,
    [DeviceType]          VARCHAR (30)   NULL,
    [DeviceBrand]         VARCHAR (30)   NULL,
    [DeviceBrandCode]     VARCHAR (30)   NULL,
    [DeviceBrandUrl]      VARCHAR (1000) NULL,
    [DeviceName]          VARCHAR (30)   NULL,
    [BrowserName]         VARCHAR (30)   NULL,
    [BrowserVersion]      VARCHAR (30)   NULL,
    [BrowserVersionMajor] VARCHAR (30)   NULL,
    [BrowserEngine]       VARCHAR (30)   NULL,
    [isCrawler]           BIT            NULL,
    [CrawlerCategory]     VARCHAR (30)   NULL,
    [CrawlerLastSeen]     VARCHAR (30)   NULL
);

