CREATE LOGIN [ChrisN]
    WITH PASSWORD = N'~!sq#kjy0GDqH!kq~qfgyeiVmsFT7_&#$!~<iqBaixmbhc4w', SID = 0x6AD1D630ABB9644DB9DE848454D93EFE, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

