CREATE TABLE [Staging].[__ROCShopperSegment_PreSelection_Archived] (
    [ID]                        INT           IDENTITY (1, 1) NOT NULL,
    [EmailDate]                 DATE          NULL,
    [PartnerID]                 CHAR (4)      NULL,
    [StartDate]                 DATE          NULL,
    [EndDate]                   DATE          NULL,
    [NonCoreBaseOffer]          BIT           NULL,
    [MarketableByEmail]         BIT           NULL,
    [PaymentMethodsAvailable]   VARCHAR (10)  NULL,
    [OfferID]                   VARCHAR (40)  NULL,
    [Throttling]                VARCHAR (200) NULL,
    [ClientServicesRef]         VARCHAR (10)  NULL,
    [OutputTableName]           VARCHAR (100) NULL,
    [CampaignName]              VARCHAR (250) NULL,
    [SelectionDate]             VARCHAR (11)  NULL,
    [DeDupeAgainstCampaigns]    VARCHAR (50)  NULL,
    [NotIn_TableName1]          VARCHAR (100) NULL,
    [NotIn_TableName2]          VARCHAR (100) NULL,
    [NotIn_TableName3]          VARCHAR (100) NULL,
    [NotIn_TableName4]          VARCHAR (100) NULL,
    [SelectedInAnotherCampaign] VARCHAR (20)  NULL,
    [CampaignTypeID]            CHAR (1)      NULL,
    [CoreSpendersToPrime]       CHAR (1)      NULL,
    [CustomerBaseOfferDate]     DATE          NULL,
    [SelectionRun]              BIT           NULL
);

