CREATE TABLE [Staging].[BMS_Reconciliation_Match_Trans] (
    [ID]                             INT           NOT NULL,
    [AddedDate]                      DATETIME      NOT NULL,
    [VectorID]                       INT           NOT NULL,
    [VectorMajorID]                  INT           NOT NULL,
    [VectorMinorID]                  INT           NOT NULL,
    [PanID]                          INT           NULL,
    [MerchantID]                     NVARCHAR (19) NOT NULL,
    [Amount]                         SMALLMONEY    NOT NULL,
    [TransactionDate]                DATETIME      NOT NULL,
    [Status]                         INT           NOT NULL,
    [RetailOutletID]                 INT           NULL,
    [RewardStatus]                   INT           NOT NULL,
    [Reversed]                       BIT           NOT NULL,
    [AffiliateCommissionShare]       FLOAT (53)    NULL,
    [AffiliateCommissionAmount]      SMALLMONEY    NULL,
    [PartnerCommissionRate]          FLOAT (53)    NULL,
    [PartnerCommissionAmount]        SMALLMONEY    NULL,
    [VatRate]                        FLOAT (53)    NULL,
    [VatAmount]                      SMALLMONEY    NULL,
    [InsertedManually]               BIT           NULL,
    [InvoiceID]                      INT           NULL,
    [ReportedToAffiliate]            BIT           NULL,
    [ReportedToAffiliateDate]        DATETIME      NULL,
    [BillerID]                       INT           NULL,
    [BillerCollectionDate]           DATETIME      NULL,
    [BillerPaymentID]                INT           NULL,
    [BillerPaymentDate]              DATETIME      NULL,
    [PartnerCommissionRuleID]        INT           NULL,
    [AffiliateCommissionShareRuleID] INT           NULL,
    [AnalysisStartDate]              DATE          NULL,
    [AnalysisEndDate]                DATE          NULL,
    CONSTRAINT [PK_BMS_Reconciliation_Match_Trans] PRIMARY KEY CLUSTERED ([ID] ASC)
);

