CREATE TABLE [Staging].[BrandMIDMCC] (
    [BrandMIDID] INT         IDENTITY (1, 1) NOT NULL,
    [MCC]        VARCHAR (4) NULL,
    CONSTRAINT [PK_BrandMIDMCC] PRIMARY KEY CLUSTERED ([BrandMIDID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_BrandMIDMCC_MCC]
    ON [Staging].[BrandMIDMCC]([MCC] ASC);

