CREATE TABLE [Staging].[CampaignPlanning_TriggerMember] (
    [ID]                     INT          IDENTITY (1, 1) NOT NULL,
    [FanID]                  INT          NOT NULL,
    [PartnerID]              INT          NOT NULL,
    [HTMID]                  TINYINT      NULL,
    [CompetitorShopper4wk]   BIT          DEFAULT ((0)) NOT NULL,
    [Homemover]              BIT          DEFAULT ((0)) NOT NULL,
    [Lapser]                 BIT          DEFAULT ((0)) NOT NULL,
    [Student]                BIT          DEFAULT ((0)) NOT NULL,
    [AcquireMember]          BIT          DEFAULT ((0)) NOT NULL,
    [SuperSegmentID]         TINYINT      NULL,
    [Total_SalesValue_Wk1]   MONEY        NULL,
    [Total_Transactions_Wk1] MONEY        NULL,
    [HeatMapID]              SMALLINT     NULL,
    [Gender]                 CHAR (1)     NULL,
    [MinAge]                 SMALLINT     NULL,
    [MaxAge]                 SMALLINT     NULL,
    [CAMEO_CODE_GROUP]       VARCHAR (2)  NULL,
    [SocialClass]            VARCHAR (2)  NULL,
    [DriveTimeBandID]        TINYINT      NULL,
    [ResponseIndexScore]     FLOAT (53)   NULL,
    [NonCoreBO_CSRef]        VARCHAR (12) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90, DATA_COMPRESSION = PAGE)
);

