CREATE TABLE [Staging].[ConsumerTransactionStage] (
    [FileID]                INT          NOT NULL,
    [RowNum]                INT          NOT NULL,
    [BrandMIDID]            INT          NOT NULL,
    [ConsumerCombinationID] INT          NULL,
    [BankID]                TINYINT      NOT NULL,
    [LocationAddress]       VARCHAR (50) NOT NULL,
    [LocationID]            INT          NULL,
    [MCC]                   VARCHAR (4)  NOT NULL,
    [MCCID]                 SMALLINT     NULL,
    [CardholderPresentData] VARCHAR (1)  NOT NULL,
    [CardholderPresentID]   TINYINT      NULL,
    [TranDate]              DATE         NULL,
    [CINID]                 INT          NOT NULL,
    [PostStatus]            CHAR (1)     NOT NULL,
    [Amount]                MONEY        NOT NULL,
    [IsRefund]              BIT          NULL,
    [IsOnline]              BIT          NULL,
    [InputModeID]           TINYINT      NULL,
    [PostStatusID]          TINYINT      NULL,
    [OriginatorID]          VARCHAR (11) NOT NULL,
    [SecondaryID]           INT          NULL,
    CONSTRAINT [PK_Staging_ConsumerTransactionStage] PRIMARY KEY CLUSTERED ([FileID] ASC, [RowNum] ASC)
);

