CREATE TABLE [Staging].[FlashOfferReport_ReportData] (
    [IronOfferID]         INT          NOT NULL,
    [StartDate]           DATE         NOT NULL,
    [EndDate]             DATE         NOT NULL,
    [OfferSetupStartDate] DATE         NOT NULL,
    [OfferSetupEndDate]   DATE         NOT NULL,
    [PeriodType]          VARCHAR (25) NOT NULL,
    [RetailerID]          INT          NULL,
    [PublisherID]         INT          NULL,
    [isWarehouse]         BIT          NULL,
    [ControlGroupTypeID]  INT          NOT NULL,
    [Channel]             BIT          NULL,
    [Threshold]           BIT          NULL,
    [Cardholders_E]       INT          NULL,
    [Cardholders_C]       INT          NULL,
    [Sales]               MONEY        NULL,
    [Sales_E]             MONEY        NULL,
    [Sales_C]             MONEY        NULL,
    [Trans]               INT          NULL,
    [Trans_E]             INT          NULL,
    [Trans_C]             INT          NULL,
    [Spenders]            INT          NULL,
    [Spenders_E]          INT          NULL,
    [Spenders_C]          INT          NULL,
    [Investment]          MONEY        NULL,
    [SPC]                 FLOAT (53)   NULL,
    [SPS]                 FLOAT (53)   NULL,
    [RR]                  FLOAT (53)   NULL,
    [ATV]                 FLOAT (53)   NULL,
    [ATF]                 FLOAT (53)   NULL,
    [SPC_C]               FLOAT (53)   NULL,
    [SPS_C]               FLOAT (53)   NULL,
    [RR_C]                FLOAT (53)   NULL,
    [ATV_C]               FLOAT (53)   NULL,
    [ATF_C]               FLOAT (53)   NULL,
    [SPC_E]               FLOAT (53)   NULL,
    [SPS_E]               FLOAT (53)   NULL,
    [RR_E]                FLOAT (53)   NULL,
    [ATV_E]               FLOAT (53)   NULL,
    [ATF_E]               FLOAT (53)   NULL,
    [RR_Uplift]           FLOAT (53)   NULL,
    [ATV_Uplift]          FLOAT (53)   NULL,
    [ATF_Uplift]          FLOAT (53)   NULL,
    [Sales_Uplift]        FLOAT (53)   NULL,
    [IncSales]            MONEY        NULL,
    [IncSpenders]         INT          NULL,
    [SalesToCostRatio]    FLOAT (53)   NULL,
    [CalculationDate]     DATE         NOT NULL,
    CONSTRAINT [PK_FlashOfferReport_ReportData] PRIMARY KEY CLUSTERED ([IronOfferID] ASC, [ControlGroupTypeID] ASC, [StartDate] ASC, [EndDate] ASC, [PeriodType] ASC, [CalculationDate] ASC) WITH (FILLFACTOR = 80)
);

