CREATE TABLE [Staging].[Onboarding_Matcher_Mastercard_ActiveList] (
    [ID]                    INT           IDENTITY (1, 1) NOT NULL,
    [MERCH_SITE_ID]         VARCHAR (255) NULL,
    [LOC_ID]                VARCHAR (255) NULL,
    [SHORT_DBA_NAME]        VARCHAR (255) NULL,
    [MERCHANT_DBA_NAME]     VARCHAR (255) NULL,
    [MERCHANT_STREET_ADDR]  VARCHAR (255) NULL,
    [CITY_NAME]             VARCHAR (255) NULL,
    [STATE_PROVINCE_CODE]   VARCHAR (255) NULL,
    [MERCHANT_POSTAL_CODE]  VARCHAR (255) NULL,
    [COUNTRY_CODE]          VARCHAR (255) NULL,
    [SET_ID]                VARCHAR (255) NULL,
    [BGN_DT]                VARCHAR (255) NULL,
    [EFF_DT]                VARCHAR (255) NULL,
    [END_DT]                VARCHAR (255) NULL,
    [CHAIN_ID]              VARCHAR (255) NULL,
    [MERCH_OWNR_TXT]        VARCHAR (255) NULL,
    [ACQ_MERCH_ID]          VARCHAR (255) NULL,
    [UPDT_DT]               VARCHAR (255) NULL,
    [AUTH_ACQ_MERCH_ID]     VARCHAR (255) NULL,
    [FLD1_NAM]              VARCHAR (255) NULL,
    [FLD1_VAL_TXT]          VARCHAR (255) NULL,
    [FLD2_NAM]              VARCHAR (255) NULL,
    [FLD2_VAL_TXT]          VARCHAR (255) NULL,
    [AGGREGATE_MERCHANT_ID] VARCHAR (255) NULL,
    [BRICK_TRAN_PCT]        VARCHAR (255) NULL,
    [ECMRC_TRAN_PCT]        VARCHAR (255) NULL,
    [NON_STOR_RTL_TRAN_PCT] VARCHAR (255) NULL,
    [InsertDate]            DATE          DEFAULT (getdate()) NULL
);

