CREATE TABLE [Staging].[RBSG_MonthlyReport_MonthByMonthComms] (
    [SendDate]             DATE        NULL,
    [Total_EmailsSent]     INT         NULL,
    [Unique_CustomerCount] INT         NULL,
    [Opens]                INT         NULL,
    [Opens_Pct]            FLOAT (53)  NULL,
    [Links_Clicked]        INT         NULL,
    [LinkClicked_Pct]      FLOAT (53)  NULL,
    [Unsubscribes]         INT         NULL,
    [Unsubscribe_Pct]      FLOAT (53)  NULL,
    [Avg_EmailsSent]       INT         NULL,
    [Avg_CustomerCount]    INT         NULL,
    [Avg_Opens]            INT         NULL,
    [Avg_Open_Pct]         FLOAT (53)  NULL,
    [Avg_Links_Clicked]    INT         NULL,
    [Avg_Links_Pct]        FLOAT (53)  NULL,
    [Avg_Unsubscribes]     INT         NULL,
    [Avg_Unsubscribes_Pct] FLOAT (53)  NULL,
    [WhichMonth]           VARCHAR (2) NOT NULL,
    [OffersPromoted]       INT         NULL,
    [AboveBaseOffers]      INT         NULL,
    [BaseOffers]           INT         NULL,
    [Avg_OffersPromoted]   INT         NULL,
    [Avg_AboveBaseOffers]  INT         NULL,
    [Avg_BaseOffers]       INT         NULL
);

