CREATE TABLE [Staging].[VocaFile_OriginatorRecord] (
    [RecordType]                 VARCHAR (MAX) NULL,
    [AmendmentDate]              DATE          NULL,
    [ServiceUserNumber]          INT           NULL,
    [ServiceUserName]            VARCHAR (MAX) NULL,
    [SchemeAdminAddresseeName]   VARCHAR (MAX) NULL,
    [SchemeAdminPostalName]      VARCHAR (MAX) NULL,
    [SchemeAdminAddressLine1]    VARCHAR (MAX) NULL,
    [SchemeAdminAddressLine2]    VARCHAR (MAX) NULL,
    [SchemeAdminAddressLine3]    VARCHAR (MAX) NULL,
    [SchemeAdminAddressLine4]    VARCHAR (MAX) NULL,
    [SchemeAdminPostcode]        VARCHAR (MAX) NULL,
    [SchemeAdminTelephoneNumber] VARCHAR (MAX) NULL,
    [SchemeAdminFaxNumber]       VARCHAR (MAX) NULL,
    [UserNameAddLine1]           VARCHAR (MAX) NULL,
    [UserNameAddLine2]           VARCHAR (MAX) NULL,
    [UserNameAddLine3]           VARCHAR (MAX) NULL,
    [UserNameAddLine4]           VARCHAR (MAX) NULL,
    [UserNameAddLine5]           VARCHAR (MAX) NULL,
    [UserNameAddLine6]           VARCHAR (MAX) NULL,
    [UserPostcode]               VARCHAR (MAX) NULL,
    [SponsorBankCode]            VARCHAR (MAX) NULL,
    [OriginatorStatus]           VARCHAR (MAX) NULL,
    [AUDDISStatus]               VARCHAR (MAX) NULL,
    [PriorNotificationPeriod]    VARCHAR (MAX) NULL,
    [DormantPeriod]              VARCHAR (MAX) NULL,
    [MarketSegment]              VARCHAR (MAX) NULL,
    [AmalgamationFlag]           VARCHAR (MAX) NULL,
    [PadderRecord]               VARCHAR (MAX) NULL,
    [Reserved]                   VARCHAR (MAX) NULL
);

