CREATE TABLE [Staging].[WarehousePerformanceMonitor] (
    [MonitorID]                INT           IDENTITY (1, 1) NOT NULL,
    [MonitorDate]              SMALLDATETIME DEFAULT (getdate()) NOT NULL,
    [FullScansSec]             FLOAT (53)    NOT NULL,
    [IndexSearchesSec]         FLOAT (53)    NOT NULL,
    [PageSplitsSec]            FLOAT (53)    NOT NULL,
    [WorkFilesCreatedSec]      FLOAT (53)    NOT NULL,
    [WorkTablesCreatedSec]     FLOAT (53)    NOT NULL,
    [LogBytesFlushedSec]       FLOAT (53)    NOT NULL,
    [LogFlushWaitsSec]         FLOAT (53)    NOT NULL,
    [LogFlushesSec]            FLOAT (53)    NOT NULL,
    [FreeListStallsSec]        FLOAT (53)    NOT NULL,
    [LazyWritesSec]            FLOAT (53)    NOT NULL,
    [CheckpointPagesSec]       FLOAT (53)    NOT NULL,
    [PageLookupsSec]           FLOAT (53)    NOT NULL,
    [PageReadsSec]             FLOAT (53)    NOT NULL,
    [PageWritesSec]            FLOAT (53)    NOT NULL,
    [ReadAheadsSec]            FLOAT (53)    NOT NULL,
    [BatchRequestsSec]         FLOAT (53)    NOT NULL,
    [SQLCompilationsSec]       FLOAT (53)    NOT NULL,
    [SQLRecompilationsSec]     FLOAT (53)    NOT NULL,
    [AttentionRateSec]         FLOAT (53)    NOT NULL,
    [LockWaitsSec]             FLOAT (53)    NOT NULL,
    [LockRequestsSec]          FLOAT (53)    NOT NULL,
    [LockTimeoutsSec]          FLOAT (53)    NOT NULL,
    [NumberOfDeadlocksSec]     FLOAT (53)    NOT NULL,
    [TableLockEscalationsSec]  FLOAT (53)    NOT NULL,
    [DataFileSizeKB]           BIGINT        NOT NULL,
    [LogFileSizeKB]            BIGINT        NOT NULL,
    [LogFileUsedSizeKB]        BIGINT        NOT NULL,
    [LogFlushWaitTime]         BIGINT        NOT NULL,
    [PageLifeExpectancy]       BIGINT        NOT NULL,
    [DatabasePages]            BIGINT        NOT NULL,
    [FreePages]                BIGINT        NOT NULL,
    [StolenPagesSec]           BIGINT        NOT NULL,
    [BufferCacheHitRatio]      FLOAT (53)    NOT NULL,
    [AverageLatchWaitTimeMS]   FLOAT (53)    NOT NULL,
    [AverageLockWaitTimeMS]    FLOAT (53)    NOT NULL,
    [WorkTablesFromCacheRatio] FLOAT (53)    NOT NULL,
    PRIMARY KEY CLUSTERED ([MonitorID] ASC)
);

