CREATE TABLE [MI].[ALS_Members_Report_Data] (
    [ID]                INT          IDENTITY (1, 1) NOT NULL,
    [IsRecentActivity]  BIT          NULL,
    [RetailerID]        INT          NULL,
    [AnalysisStartDate] DATE         NULL,
    [CycleStartDate]    DATE         NULL,
    [CycleEndDate]      DATE         NULL,
    [AnchorSegmentType] VARCHAR (50) NULL,
    [CycleSegmentType]  VARCHAR (50) NULL,
    [CycleMembers]      INT          NULL,
    [Transactions]      INT          NULL,
    [Spenders]          INT          NULL,
    [Spend]             MONEY        NULL,
    [Investment]        MONEY        NULL,
    [CycleMembers_C]    INT          NULL,
    [Transactions_C]    INT          NULL,
    [Spenders_C]        INT          NULL,
    [Spend_C]           MONEY        NULL,
    [SPC]               FLOAT (53)   NULL,
    [SPS]               FLOAT (53)   NULL,
    [RR]                FLOAT (53)   NULL,
    [ATV]               FLOAT (53)   NULL,
    [ATF]               FLOAT (53)   NULL,
    [SPC_C]             FLOAT (53)   NULL,
    [SPS_C]             FLOAT (53)   NULL,
    [RR_C]              FLOAT (53)   NULL,
    [ATV_C]             FLOAT (53)   NULL,
    [ATF_C]             FLOAT (53)   NULL,
    [AdjustmentFactor]  FLOAT (53)   NULL,
    [RR_Uplift]         FLOAT (53)   NULL,
    [ATV_Uplift]        FLOAT (53)   NULL,
    [ATF_Uplift]        FLOAT (53)   NULL,
    [Sales_Uplift]      FLOAT (53)   NULL,
    [IncSales]          MONEY        NULL,
    [IncSpenders]       INT          NULL,
    CONSTRAINT [PK_ALS_Members_Report_Data] PRIMARY KEY CLUSTERED ([ID] ASC)
);

