CREATE TABLE [MI].[CampaignReport_CheckFlagsLTE] (
    [ID]                                        INT            IDENTITY (1, 1) NOT NULL,
    [ClientServicesRef]                         VARCHAR (40)   NOT NULL,
    [StartDate]                                 DATE           NOT NULL,
    [MaxEndDate]                                DATE           NULL,
    [InternalControlGroup]                      VARCHAR (100)  NOT NULL,
    [ExternalControlGroup]                      VARCHAR (100)  NOT NULL,
    [Cardholders]                               BIGINT         NULL,
    [Sales]                                     MONEY          NULL,
    [Commission]                                MONEY          NULL,
    [IncrementalSales_Internal]                 REAL           NULL,
    [IncrementalSales_External]                 REAL           NULL,
    [Cardholders_Awareness]                     BIGINT         NULL,
    [Sales_Awareness]                           MONEY          NULL,
    [IncrementalSales_Internal_Awareness]       REAL           NULL,
    [IncrementalSales_External_Awareness]       REAL           NULL,
    [Cardholders_Loyalty]                       BIGINT         NULL,
    [Sales_Loyalty]                             MONEY          NULL,
    [IncrementalSales_Internal_Loyalty]         REAL           NULL,
    [IncrementalSales_External_Loyalty]         REAL           NULL,
    [AwarenessCheck]                            VARCHAR (13)   NOT NULL,
    [LoyaltyCheck]                              VARCHAR (13)   NOT NULL,
    [InsertTime]                                DATETIME       CONSTRAINT [DF_MI_CampaignReport_CheckFlagsLTE_InsertTime] DEFAULT (getdate()) NULL,
    [CampaignName]                              VARCHAR (500)  NULL,
    [UpliftCardholders_Perc_Internal_Awareness] DECIMAL (4, 3) NULL,
    [UpliftCardholders_Perc_External_Awareness] DECIMAL (4, 3) NULL,
    [UpliftCardholders_Perc_Internal_Loyalty]   DECIMAL (4, 3) NULL,
    [UpliftCardholders_Perc_External_Loyalty]   DECIMAL (4, 3) NULL,
    [Archived]                                  BIT            CONSTRAINT [DF_CampaignReport_CheckFlagsLTE_Archived] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_MI_CampaignReport_CheckFlagsLTE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

