CREATE TABLE [MI].[CBP_DailyMIReport] (
    [CUSTOMER ID]                         VARCHAR (10)  NOT NULL,
    [E-MAIL ADDRESS]                      VARCHAR (255) NULL,
    [MOBILE NUMBER]                       VARCHAR (20)  NULL,
    [BANK ID]                             VARCHAR (4)   NOT NULL,
    [IS MARKETING SUPPRESSED SMS]         CHAR (1)      NULL,
    [IS MARKETING SUPPRESSED EMAIL]       CHAR (1)      NULL,
    [IS MARKETING SUPPRESSED DM]          CHAR (1)      NULL,
    [OPTED OUT]                           CHAR (1)      NULL,
    [OPTED OUT DATE]                      DATE          NULL,
    [CURRENTLY ACTIVE]                    CHAR (1)      NULL,
    [ACTIVATION CHANNEL]                  TINYINT       NULL,
    [ACTIVATED BY CREDIT CARD]            CHAR (1)      NULL,
    [ACTIVATED DATE]                      DATE          NULL,
    [IS REGISTERED]                       CHAR (1)      NULL,
    [TOTAL TRANSACTION AMOUNT DEBIT]      MONEY         NULL,
    [TOTAL TRANSACTION AMOUNT CREDIT]     MONEY         NULL,
    [TOTAL TRANSACTION AMOUNT DD]         MONEY         NULL,
    [TOTAL TRANSACTION COUNT DEBIT]       INT           NULL,
    [TOTAL TRANSACTION COUNT CREDIT]      INT           NULL,
    [TOTAL TRANSACTION COUNT DD]          INT           NULL,
    [CASHBACK BALANCE - PENDING]          MONEY         NULL,
    [CASHBACK BALANCE – CLEARED]          MONEY         NULL,
    [TOTAL REDEEMED VALUE]                MONEY         NULL,
    [REDEEMED VALUE CASH TO BANK ACCOUNT] MONEY         NULL,
    [REDEEMED VALUE CASH TO CREDIT CARD]  MONEY         NULL,
    [REDEEMED VALUE IN TRADEUP]           MONEY         NULL,
    [REDEEMED VALUE IN CHARITY]           MONEY         NULL,
    [CONTACT HISTORY]                     INT           NULL,
    [EMAIL HARDBOUNCED]                   BIT           NULL,
    CONSTRAINT [PK_MI_CBP_DailyMIReport] PRIMARY KEY CLUSTERED ([CUSTOMER ID] ASC, [BANK ID] ASC)
);

