CREATE TABLE [MI].[RBSPortal_Customer_Check] (
    [FanID]                  INT          NOT NULL,
    [DOB]                    DATE         NULL,
    [ActivatedDate]          DATE         NOT NULL,
    [DeactivatedDate]        DATE         NULL,
    [OptedOutDate]           DATE         NULL,
    [GenderID]               TINYINT      NOT NULL,
    [AgeBandID]              TINYINT      NULL,
    [BankID]                 TINYINT      NULL,
    [RainbowID]              TINYINT      NULL,
    [ChannelPreferenceID]    TINYINT      CONSTRAINT [DF_ChannelPreferenceID_Check] DEFAULT ((3)) NOT NULL,
    [JourneyStageID]         TINYINT      NULL,
    [ContactByEmail]         INT          NOT NULL,
    [ContactByPhone]         INT          NOT NULL,
    [ContactBySMS]           INT          NOT NULL,
    [ContactByPost]          INT          NOT NULL,
    [IsLapsed]               BIT          NOT NULL,
    [ActivationMethodID]     TINYINT      NOT NULL,
    [JourneyStageDetailedID] TINYINT      NOT NULL,
    [SourceUID]              VARCHAR (20) NULL,
    [EmailEngaged]           BIT          NOT NULL,
    [Registered]             BIT          NOT NULL,
    CONSTRAINT [MI_RBSPortal_Customer_Check] PRIMARY KEY CLUSTERED ([FanID] ASC)
);

