CREATE TABLE [MI].[RetailerReportSplitMonthly_OLD] (
    [ID]                     INT              IDENTITY (1, 1) NOT NULL,
    [MonthID]                INT              NOT NULL,
    [SplitID]                SMALLINT         NOT NULL,
    [SplitDesc]              VARCHAR (50)     NOT NULL,
    [StatusTypeID]           SMALLINT         NOT NULL,
    [StatusTypeDesc]         VARCHAR (50)     NOT NULL,
    [PartnerID]              INT              NULL,
    [PartnerGroupID]         INT              NULL,
    [ActivatedTrans]         INT              NULL,
    [ActivatedSales]         MONEY            NULL,
    [ActivatedSpender]       INT              NOT NULL,
    [ActivatedCommission]    MONEY            NOT NULL,
    [PostActivatedTrans]     INT              NULL,
    [PostActivatedSales]     MONEY            NULL,
    [PostActivatedSpender]   INT              NULL,
    [ControlTrans]           INT              NULL,
    [ControlCardholderSales] MONEY            NULL,
    [ControlSpender]         INT              NOT NULL,
    [ControlCardholder]      INT              NOT NULL,
    [ActivatedCardholders]   INT              NOT NULL,
    [AdjFactorSPC]           DECIMAL (18, 16) NOT NULL,
    [AdjFactorRR]            DECIMAL (18, 16) NOT NULL,
    [AdjFactorSPS]           DECIMAL (18, 16) NOT NULL,
    [AdjFactorATV]           DECIMAL (18, 16) NOT NULL,
    [AdjFactorATF]           DECIMAL (18, 16) NOT NULL,
    [AdjFactorTPC]           DECIMAL (18, 16) NULL,
    [Label]                  VARCHAR (50)     NOT NULL,
    [IncrementalSales]       MONEY            NULL,
    [IncrementalTrans]       FLOAT (53)       NULL,
    [IncrementalSpenders]    FLOAT (53)       NULL,
    [ClientServicesRef]      VARCHAR (50)     NULL,
    [Split_Use_For_Report]   INT              NULL,
    [Status_Use_For_Report]  INT              NULL,
    [Cumulative]             TINYINT          NULL,
    CONSTRAINT [PK_MI_RetailerReportSplitMonthly] PRIMARY KEY CLUSTERED ([ID] ASC)
);

