CREATE TABLE [MI].[RetailerReportSignificance] (
    [ProgramID]                   INT           NOT NULL,
    [PartnerGroupID]              INT           NOT NULL,
    [PartnerID]                   INT           NOT NULL,
    [ClientServiceRef]            NVARCHAR (10) NULL,
    [PaymentTypeID]               INT           NOT NULL,
    [ChannelID]                   INT           NOT NULL,
    [CustomerAttributeID]         INT           NOT NULL,
    [Mid_SplitID]                 INT           NOT NULL,
    [CumulativeTypeID]            INT           NOT NULL,
    [PeriodTypeID]                INT           NOT NULL,
    [DateID]                      INT           NOT NULL,
    [UpliftSales]                 FLOAT (53)    NULL,
    [UpliftSpenders]              FLOAT (53)    NULL,
    [UpliftSPS]                   FLOAT (53)    NULL,
    [UpliftSales_LowerBond80]     FLOAT (53)    NULL,
    [UpliftSales_UpperBond80]     FLOAT (53)    NULL,
    [UpliftSpenders_LowerBond80]  FLOAT (53)    NULL,
    [UpliftSpenders_UpperBond80]  FLOAT (53)    NULL,
    [UpliftSPS_LowerBond80]       FLOAT (53)    NULL,
    [UpliftSPS_UpperBond80]       FLOAT (53)    NULL,
    [UpliftSales_Significance]    VARCHAR (10)  NOT NULL,
    [UpliftSpenders_Significance] VARCHAR (10)  NOT NULL,
    [UpliftSPS_Significance]      VARCHAR (10)  NOT NULL
);

