CREATE TABLE [MI].[RetailerReportMetric] (
    [ID]                       INT            IDENTITY (1, 1) NOT NULL,
    [ProgramID]                INT            NOT NULL,
    [PartnerGroupID]           INT            NOT NULL,
    [PartnerID]                INT            NOT NULL,
    [ClientServiceRef]         NVARCHAR (10)  NOT NULL,
    [PaymentTypeID]            INT            NOT NULL,
    [ChannelID]                INT            NOT NULL,
    [CustomerAttributeID]      INT            NOT NULL,
    [Mid_SplitID]              INT            NOT NULL,
    [CumulativeTypeID]         INT            NOT NULL,
    [PeriodTypeID]             INT            NOT NULL,
    [DateID]                   INT            NOT NULL,
    [CurrencyID]               INT            NOT NULL,
    [CurrencyAdj]              FLOAT (53)     NOT NULL,
    [Cardholders]              INT            NULL,
    [Sales]                    MONEY          NULL,
    [Transactions]             INT            NULL,
    [Spenders]                 INT            NULL,
    [Commission]               MONEY          NULL,
    [UpliftSales]              FLOAT (53)     NULL,
    [UpliftTransactions]       FLOAT (53)     NULL,
    [UpliftSpenders]           FLOAT (53)     NULL,
    [IncrementalSales]         MONEY          NULL,
    [IncrementalTransactions]  FLOAT (53)     NULL,
    [IncrementalSpenders]      FLOAT (53)     NULL,
    [IncrementalMargin]        FLOAT (53)     NULL,
    [ATVUplift]                FLOAT (53)     NULL,
    [ATFUplift]                FLOAT (53)     NULL,
    [DriverTreeATVIncremental] FLOAT (53)     NULL,
    [DriverTreeATFIncremental] FLOAT (53)     NULL,
    [DriverTreeRRIncremental]  FLOAT (53)     NULL,
    [ATV]                      FLOAT (53)     NULL,
    [ATF]                      FLOAT (53)     NULL,
    [RR]                       FLOAT (53)     NULL,
    [CostPerAcquisition]       MONEY          NULL,
    [TotalSalesROI]            MONEY          NULL,
    [IncrementalSalesROI]      MONEY          NULL,
    [FinancialROI]             MONEY          NULL,
    [SPSUplift]                FLOAT (53)     NULL,
    [Margin]                   FLOAT (53)     NULL,
    [ContractROI]              DECIMAL (8, 5) NULL,
    [ContractTargetUplift]     DECIMAL (8, 5) NULL,
    [RewardTargetUplift]       DECIMAL (8, 5) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([ProgramID] ASC, [PartnerGroupID] ASC, [PartnerID] ASC, [ClientServiceRef] ASC, [PaymentTypeID] ASC, [ChannelID] ASC, [CustomerAttributeID] ASC, [Mid_SplitID] ASC, [CumulativeTypeID] ASC, [PeriodTypeID] ASC, [DateID] ASC, [CurrencyID] ASC)
);

