CREATE TABLE [MI].[SchemeUpliftTrans_MemberSales] (
    [ID]                      INT           IDENTITY (1, 1) NOT NULL,
    [FileID]                  INT           NOT NULL,
    [RowNum]                  INT           NOT NULL,
    [PartnerID]               INT           NOT NULL,
    [ClientServiceRef]        NVARCHAR (30) NOT NULL,
    [PaymentTypeID]           INT           NOT NULL,
    [ChannelID]               TINYINT       NOT NULL,
    [CustomerAttributeID_0]   INT           NOT NULL,
    [CustomerAttributeID_0BP] INT           NOT NULL,
    [CustomerAttributeID_1]   INT           NOT NULL,
    [CustomerAttributeID_1BP] INT           NOT NULL,
    [CustomerAttributeID_2]   INT           NOT NULL,
    [CustomerAttributeID_2BP] INT           NOT NULL,
    [CustomerAttributeID_3]   INT           NOT NULL,
    [Mid_SplitID]             INT           NULL,
    [CumulativeTypeID]        INT           NOT NULL,
    [PeriodTypeID]            INT           NOT NULL,
    [DateID]                  INT           NOT NULL,
    [MembersSales]            MONEY         NOT NULL,
    [FanID]                   INT           NOT NULL,
    [InWorkingOfferRange]     BIT           NULL,
    CONSTRAINT [PK_MI_SchemeUpliftTrans_MemberSales] PRIMARY KEY CLUSTERED ([ID] ASC)
);

