CREATE TABLE [MI].[Staging_SchemeTransaction] (
    [MatchID]             INT      NULL,
    [FanID]               INT      NULL,
    [Spend]               MONEY    NULL,
    [Earnings]            MONEY    NULL,
    [AddedDate]           DATE     NULL,
    [BrandID]             SMALLINT NULL,
    [OfferAboveBase]      BIT      NULL,
    [TranWeekID]          SMALLINT NULL,
    [TranMonthID]         SMALLINT NULL,
    [IsEarn]              BIT      NULL,
    [SpendAtBaseCust]     INT      NULL,
    [SpendAboveBaseCust]  INT      NULL,
    [EarnAtBaseCust]      INT      NULL,
    [EarnAboveBaseCust]   INT      NULL,
    [EarnCust]            INT      NULL,
    [AddedDateTime]       DATETIME NULL,
    [IronOfferID]         INT      NULL,
    [RBSFunded]           TINYINT  NULL,
    [SpendAtBase]         MONEY    NULL,
    [SpendAboveBase]      MONEY    NULL,
    [EarningsAtBase]      MONEY    NULL,
    [EarningsAboveBase]   MONEY    NULL,
    [GenderID]            TINYINT  NULL,
    [AgeBandID]           TINYINT  NULL,
    [BankID]              TINYINT  NULL,
    [RainbowID]           TINYINT  NULL,
    [ChannelPreferenceID] TINYINT  NULL,
    [ActivationMethodID]  TINYINT  NULL
);

