CREATE TABLE [Staging].[__PartnerTrans_Archived] (
    [MatchID]                         INT        NOT NULL,
    [FanID]                           INT        NOT NULL,
    [TransactionDate]                 DATE       NULL,
    [AddedDate]                       DATE       NULL,
    [OutletID]                        INT        NULL,
    [TransactionAmount]               SMALLMONEY NOT NULL,
    [status]                          INT        NOT NULL,
    [PartnerCommissionRuleID]         INT        NULL,
    [rewardstatus]                    INT        NOT NULL,
    [AffiliateCommissionAmount]       SMALLMONEY NULL,
    [PartnerID]                       INT        NULL,
    [TransactionWeekStarting]         DATE       NULL,
    [TransactionMonth]                TINYINT    NULL,
    [TransactionYear]                 SMALLINT   NULL,
    [TransactionWeekStartingCampaign] DATE       NULL,
    [AddedWeekStarting]               DATE       NULL,
    [AddedMonth]                      TINYINT    NULL,
    [AddedYear]                       SMALLINT   NULL,
    [ExtremeValueFlag]                BIT        NULL,
    [IsOnline]                        BIT        NULL,
    [CardHolderPresentData]           CHAR (1)   NULL,
    [EligibleForCashBack]             BIT        NULL,
    [CommissionChargable]             MONEY      NULL,
    [CashbackEarned]                  MONEY      NULL,
    [IronOfferID]                     INT        NULL,
    [ActivationDays]                  INT        NULL,
    [AboveBase]                       INT        NULL,
    PRIMARY KEY CLUSTERED ([MatchID] ASC)
);

