CREATE TABLE [Staging].[EarnOfferExport] (
    [EmailSendID]              INT           NULL,
    [FanID]                    INT           NULL,
    [EarnOfferID_Hero_OfferID] INT           NULL,
    [EarnOfferID_1_OfferID]    INT           NULL,
    [EarnOfferID_2_OfferID]    INT           NULL,
    [EarnOfferID_3_OfferID]    INT           NULL,
    [EarnOfferID_4_OfferID]    INT           NULL,
    [EarnOfferID_5_OfferID]    INT           NULL,
    [EarnOfferID_6_OfferID]    INT           NULL,
    [EarnOfferID_7_OfferID]    INT           NULL,
    [EarnOfferID_8_OfferID]    INT           NULL,
    [EarnOfferStartDate_Hero]  DATETIME2 (7) NULL,
    [EarnOfferStartDate_1]     DATETIME2 (7) NULL,
    [EarnOfferStartDate_2]     DATETIME2 (7) NULL,
    [EarnOfferStartDate_3]     DATETIME2 (7) NULL,
    [EarnOfferStartDate_4]     DATETIME2 (7) NULL,
    [EarnOfferStartDate_5]     DATETIME2 (7) NULL,
    [EarnOfferStartDate_6]     DATETIME2 (7) NULL,
    [EarnOfferStartDate_7]     DATETIME2 (7) NULL,
    [EarnOfferStartDate_8]     DATETIME2 (7) NULL,
    [EarnOfferEndDate_Hero]    DATETIME2 (7) NULL,
    [EarnOfferEndDate_1]       DATETIME2 (7) NULL,
    [EarnOfferEndDate_2]       DATETIME2 (7) NULL,
    [EarnOfferEndDate_3]       DATETIME2 (7) NULL,
    [EarnOfferEndDate_4]       DATETIME2 (7) NULL,
    [EarnOfferEndDate_5]       DATETIME2 (7) NULL,
    [EarnOfferEndDate_6]       DATETIME2 (7) NULL,
    [EarnOfferEndDate_7]       DATETIME2 (7) NULL,
    [EarnOfferEndDate_8]       DATETIME2 (7) NULL
);

