
CREATE PROCEDURE [WHB].[InboundLoad_DIMAIN_To_DIMAIN2]
AS
BEGIN

	IF OBJECT_ID('tempdb..#DIMAIN') IS NOT NULL DROP TABLE #DIMAIN
	SELECT	SchemaName = s.name
		,	TableName = t.name
		,	ColumnName = c.name
		,	LoadDate =	CASE
							WHEN t.name LIKE 'FileCounts%' THEN 'CalendarDate'
							WHEN t.name LIKE 'WelcomeIronOfferMembers%' THEN 'ImportDate'
							ELSE 'LoadDate'
						END		
	INTO #DIMAIN
	FROM [DIMAIN].[WH_Virgin].sys.schemas s
	INNER JOIN [DIMAIN].[WH_Virgin].sys.tables t
		ON s.schema_id = t.schema_id
	INNER JOIN [DIMAIN].[WH_Virgin].sys.columns c
		ON t.object_id = c.object_id
	WHERE s.name = 'Inbound'
	ORDER BY	s.name
			,	t.name
			,	c.name

	IF OBJECT_ID('tempdb..#DIMAIN2') IS NOT NULL DROP TABLE #DIMAIN2
	SELECT	SchemaName = s.name
		,	TableName = t.name
		,	ColumnName = c.name
		,	LoadDate =	CASE
							WHEN t.name LIKE 'FileCounts%' THEN 'CalendarDate'
							WHEN t.name LIKE 'WelcomeIronOfferMembers%' THEN 'ImportDate'
							ELSE 'LoadDate'
						END						
	INTO #DIMAIN2
	FROM [DIMAIN2].[WH_Virgin].sys.schemas s
	INNER JOIN [DIMAIN2].[WH_Virgin].sys.tables t
		ON s.schema_id = t.schema_id
	INNER JOIN [DIMAIN2].[WH_Virgin].sys.columns c
		ON t.object_id = c.object_id
	WHERE s.name = 'Inbound'
	AND t.name NOT LIKE 'CustomerOffer_%'
	AND t.name NOT LIKE 'Email%'
	AND t.name NOT LIKE 'FileCounts%'
	AND t.name NOT LIKE '%Transactions_BFO%'
	AND t.name NOT LIKE '%ReprocessingCards%'
	ORDER BY	s.name
			,	t.name
			,	c.name

	IF OBJECT_ID('tempdb..#DIMAIN_ToLoad') IS NOT NULL DROP TABLE #DIMAIN_ToLoad;
	WITH
	DIMAIN_ToLoad AS (	SELECT	[d].[SchemaName]
							,	[d].[TableName]
							,	[d].[ColumnName]
							,	[d].[LoadDate]
						FROM #DIMAIN d
						WHERE EXISTS (	SELECT 1
										FROM #DIMAIN2 d2
										WHERE #DIMAIN2.[d].SchemaName = d2.SchemaName
										AND #DIMAIN2.[d].TableName = d2.TableName
										AND #DIMAIN2.[d].ColumnName = d2.ColumnName))

	SELECT	[t2].[SchemaName]
		,	[t2].[TableName]
		,	ColumnNames = STUFF((	SELECT ', ' + [t1].[ColumnName] 
									FROM DIMAIN_ToLoad t1
									WHERE t1.SchemaName = t2.SchemaName
									AND t1.TableName = t2.TableName
									FOR XML PATH ('')), 1, 1, '')
		,	[t2].[LoadDate]
	INTO #DIMAIN_ToLoad
	FROM DIMAIN_ToLoad t2
	GROUP BY	[t2].[SchemaName]
			,	[t2].[TableName]
			,	[t2].[LoadDate];
			
	/*

	SELECT	'SELECT DIMAIN = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[' + SchemaName + '].[' + TableName + '] UNION ALL SELECT DIMAIN2 = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[' + SchemaName + '].[' + TableName + ']'
	FROM #DIMAIN_ToLoad

	SELECT DIMAIN = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Accounts] UNION ALL SELECT DIMAIN2 = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Accounts]
	SELECT DIMAIN = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Balances] UNION ALL SELECT DIMAIN2 = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Balances]
	SELECT DIMAIN = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Cards] UNION ALL SELECT DIMAIN2 = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Cards]
	SELECT DIMAIN = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Customers] UNION ALL SELECT DIMAIN2 = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Customers]
	SELECT DIMAIN = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill] UNION ALL SELECT DIMAIN2 = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill]
	SELECT DIMAIN = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Login] UNION ALL SELECT DIMAIN2 = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Login]
	SELECT DIMAIN = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions] UNION ALL SELECT DIMAIN2 = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions]
	SELECT DIMAIN = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Transactions] UNION ALL SELECT DIMAIN2 = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[Transactions]
	SELECT DIMAIN = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers] UNION ALL SELECT DIMAIN2 = COUNT(*) FROM [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers]

	SELECT	'IF OBJECT_ID(''tempdb..#' + TableName + '_DIMAIN'') IS NOT NULL DROP TABLE #' + TableName + '_DIMAIN SELECT ' + ColumnNames + ' INTO #' + TableName + '_DIMAIN FROM [DIMAIN].[WH_Virgin].[' + SchemaName + '].[' + TableName + '] WHERE ' + LoadDate + ' > DATEADD(DAY, -2, GETDATE())'
		,	'IF OBJECT_ID(''tempdb..#' + TableName + ''') IS NOT NULL DROP TABLE #' + TableName + ' SELECT ' + ColumnNames + ' INTO #' + TableName + ' FROM #' + TableName + '_DIMAIN WHERE ' + LoadDate + ' > DATEADD(DAY, -2, GETDATE()) EXCEPT SELECT ' + ColumnNames + ' FROM [DIMAIN2].[WH_Virgin].[' + SchemaName + '].[' + TableName + '] WHERE ' + LoadDate + ' > DATEADD(DAY, -2, GETDATE())'
		,	'SET IDENTITY_INSERT [WH_Virgin].[' + SchemaName + '].[' + TableName + '] ON'
		,	'INSERT INTO [DIMAIN2].[WH_Virgin].[' + SchemaName + '].[' + TableName + '] (' + ColumnNames + ') ' + 'SELECT ' + ColumnNames + ' FROM #' + TableName + ' ORDER BY ' + LoadDate
		,	'SET IDENTITY_INSERT [WH_Virgin].[' + SchemaName + '].[' + TableName + '] OFF'
	FROM #DIMAIN_ToLoad

	*/

	IF OBJECT_ID('tempdb..#Accounts_DIMAIN') IS NOT NULL DROP TABLE #Accounts_DIMAIN SELECT  [DIMAIN].[WH_Virgin].[Inbound].[Accounts].[AccountID], [DIMAIN].[WH_Virgin].[Inbound].[Accounts].[AccountRelationship], [DIMAIN].[WH_Virgin].[Inbound].[Accounts].[AccountStatus], [DIMAIN].[WH_Virgin].[Inbound].[Accounts].[AccountType], [DIMAIN].[WH_Virgin].[Inbound].[Accounts].[BankID], [DIMAIN].[WH_Virgin].[Inbound].[Accounts].[CashbackNomineeID], [DIMAIN].[WH_Virgin].[Inbound].[Accounts].[CustomerID], [DIMAIN].[WH_Virgin].[Inbound].[Accounts].[FileName], [DIMAIN].[WH_Virgin].[Inbound].[Accounts].[LoadDate] INTO #Accounts_DIMAIN FROM [DIMAIN].[WH_Virgin].[Inbound].[Accounts] WHERE [DIMAIN].[WH_Virgin].[Inbound].[Accounts].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Balances_DIMAIN') IS NOT NULL DROP TABLE #Balances_DIMAIN SELECT  [DIMAIN].[WH_Virgin].[Inbound].[Balances].[CashbackAvailable], [DIMAIN].[WH_Virgin].[Inbound].[Balances].[CashbackLifeTimeValue], [DIMAIN].[WH_Virgin].[Inbound].[Balances].[CashbackPending], [DIMAIN].[WH_Virgin].[Inbound].[Balances].[CustomerID], [DIMAIN].[WH_Virgin].[Inbound].[Balances].[FileName], [DIMAIN].[WH_Virgin].[Inbound].[Balances].[LoadDate] INTO #Balances_DIMAIN FROM [DIMAIN].[WH_Virgin].[Inbound].[Balances] WHERE [DIMAIN].[WH_Virgin].[Inbound].[Balances].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Cards_DIMAIN') IS NOT NULL DROP TABLE #Cards_DIMAIN SELECT  [DIMAIN].[WH_Virgin].[Inbound].[Cards].[AccountID], [DIMAIN].[WH_Virgin].[Inbound].[Cards].[BankID], [DIMAIN].[WH_Virgin].[Inbound].[Cards].[CardID], [DIMAIN].[WH_Virgin].[Inbound].[Cards].[FileName], [DIMAIN].[WH_Virgin].[Inbound].[Cards].[LoadDate], [DIMAIN].[WH_Virgin].[Inbound].[Cards].[PrimaryCustomerID] INTO #Cards_DIMAIN FROM [DIMAIN].[WH_Virgin].[Inbound].[Cards] WHERE [DIMAIN].[WH_Virgin].[Inbound].[Cards].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Customers_DIMAIN') IS NOT NULL DROP TABLE #Customers_DIMAIN SELECT  [DIMAIN].[WH_Virgin].[Inbound].[Customers].[BankID], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[ClosedDate], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[CustomerID], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[DateOfBirth], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[DeactivatedDate], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[EmailAddress], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[FileName], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[Forename], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[Gender], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[LoadDate], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[MarketableByEmail], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[MarketableByPaper], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[MarketableByPhone], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[MarketableBySms], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[PostCode], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[RegistrationDate], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[RewardCustomerID], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[Surname], [DIMAIN].[WH_Virgin].[Inbound].[Customers].[VirginCustomerID] INTO #Customers_DIMAIN FROM [DIMAIN].[WH_Virgin].[Inbound].[Customers] WHERE [DIMAIN].[WH_Virgin].[Inbound].[Customers].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Goodwill_DIMAIN') IS NOT NULL DROP TABLE #Goodwill_DIMAIN SELECT  [DIMAIN].[WH_Virgin].[Inbound].[Goodwill].[CustomerID], [DIMAIN].[WH_Virgin].[Inbound].[Goodwill].[FileName], [DIMAIN].[WH_Virgin].[Inbound].[Goodwill].[GoodwillAmount], [DIMAIN].[WH_Virgin].[Inbound].[Goodwill].[GoodwillDateTime], [DIMAIN].[WH_Virgin].[Inbound].[Goodwill].[GoodwillType], [DIMAIN].[WH_Virgin].[Inbound].[Goodwill].[LoadDate], [DIMAIN].[WH_Virgin].[Inbound].[Goodwill].[VirginCustomerID] INTO #Goodwill_DIMAIN FROM [DIMAIN].[WH_Virgin].[Inbound].[Goodwill] WHERE [DIMAIN].[WH_Virgin].[Inbound].[Goodwill].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Login_DIMAIN') IS NOT NULL DROP TABLE #Login_DIMAIN SELECT  [DIMAIN].[WH_Virgin].[Inbound].[Login].[CustomerID], [DIMAIN].[WH_Virgin].[Inbound].[Login].[FileName], [DIMAIN].[WH_Virgin].[Inbound].[Login].[LoadDate], [DIMAIN].[WH_Virgin].[Inbound].[Login].[LoginDateTime], [DIMAIN].[WH_Virgin].[Inbound].[Login].[LoginInformation], [DIMAIN].[WH_Virgin].[Inbound].[Login].[VirginCustomerID] INTO #Login_DIMAIN FROM [DIMAIN].[WH_Virgin].[Inbound].[Login] WHERE [DIMAIN].[WH_Virgin].[Inbound].[Login].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Redemptions_DIMAIN') IS NOT NULL DROP TABLE #Redemptions_DIMAIN SELECT  [DIMAIN].[WH_Virgin].[Inbound].[Redemptions].[Amount], [DIMAIN].[WH_Virgin].[Inbound].[Redemptions].[CustomerID], [DIMAIN].[WH_Virgin].[Inbound].[Redemptions].[FileName], [DIMAIN].[WH_Virgin].[Inbound].[Redemptions].[LoadDate], [DIMAIN].[WH_Virgin].[Inbound].[Redemptions].[RedemptionDate], [DIMAIN].[WH_Virgin].[Inbound].[Redemptions].[RedemptionType] INTO #Redemptions_DIMAIN FROM [DIMAIN].[WH_Virgin].[Inbound].[Redemptions] WHERE [DIMAIN].[WH_Virgin].[Inbound].[Redemptions].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Transactions_DIMAIN') IS NOT NULL DROP TABLE #Transactions_DIMAIN SELECT  [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[Amount], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[CardholderPresent], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[CardID], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[CardInputMode], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[CashbackAmount], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[CommissionAmount], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[CurrencyCode], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[FileName], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[LoadDate], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[MerchantClassCode], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[MerchantCountry], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[MerchantID], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[MerchantName], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[OfferID], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[TransactionDate], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[TransactionTime], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[UniqueTransactionID], [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[VirginOfferID] INTO #Transactions_DIMAIN FROM [DIMAIN].[WH_Virgin].[Inbound].[Transactions] WHERE [DIMAIN].[WH_Virgin].[Inbound].[Transactions].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#WelcomeIronOfferMembers_DIMAIN') IS NOT NULL DROP TABLE #WelcomeIronOfferMembers_DIMAIN SELECT  [DIMAIN].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[EndDate], [DIMAIN].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[HydraOfferID], [DIMAIN].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[ImportDate], [DIMAIN].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[SourceUID], [DIMAIN].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[StartDate], [DIMAIN].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[WelcomeIronOfferMembersID] INTO #WelcomeIronOfferMembers_DIMAIN FROM [DIMAIN].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers] WHERE [DIMAIN].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[ImportDate] > DATEADD(DAY, -2, GETDATE())

	IF OBJECT_ID('tempdb..#Accounts') IS NOT NULL DROP TABLE #Accounts SELECT  #Accounts_DIMAIN.[AccountID], #Accounts_DIMAIN.[AccountRelationship], #Accounts_DIMAIN.[AccountStatus], #Accounts_DIMAIN.[AccountType], #Accounts_DIMAIN.[BankID], #Accounts_DIMAIN.[CashbackNomineeID], #Accounts_DIMAIN.[CustomerID], #Accounts_DIMAIN.[FileName], #Accounts_DIMAIN.[LoadDate] INTO #Accounts FROM #Accounts_DIMAIN WHERE #Accounts_DIMAIN.[LoadDate] > DATEADD(DAY, -2, GETDATE()) EXCEPT SELECT  [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[AccountID], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[AccountRelationship], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[AccountStatus], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[AccountType], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[BankID], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[CashbackNomineeID], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[LoadDate] FROM [DIMAIN2].[WH_Virgin].[Inbound].[Accounts] WHERE [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Balances') IS NOT NULL DROP TABLE #Balances SELECT  #Balances_DIMAIN.[CashbackAvailable], #Balances_DIMAIN.[CashbackLifeTimeValue], #Balances_DIMAIN.[CashbackPending], #Balances_DIMAIN.[CustomerID], #Balances_DIMAIN.[FileName], #Balances_DIMAIN.[LoadDate] INTO #Balances FROM #Balances_DIMAIN WHERE #Balances_DIMAIN.[LoadDate] > DATEADD(DAY, -2, GETDATE()) EXCEPT SELECT  [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[CashbackAvailable], [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[CashbackLifeTimeValue], [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[CashbackPending], [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[LoadDate] FROM [DIMAIN2].[WH_Virgin].[Inbound].[Balances] WHERE [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Cards') IS NOT NULL DROP TABLE #Cards SELECT  #Cards_DIMAIN.[AccountID], #Cards_DIMAIN.[BankID], #Cards_DIMAIN.[CardID], #Cards_DIMAIN.[FileName], #Cards_DIMAIN.[LoadDate], #Cards_DIMAIN.[PrimaryCustomerID] INTO #Cards FROM #Cards_DIMAIN WHERE #Cards_DIMAIN.[LoadDate] > DATEADD(DAY, -2, GETDATE()) EXCEPT SELECT  [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[AccountID], [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[BankID], [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[CardID], [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[PrimaryCustomerID] FROM [DIMAIN2].[WH_Virgin].[Inbound].[Cards] WHERE [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Customers') IS NOT NULL DROP TABLE #Customers SELECT  #Customers_DIMAIN.[BankID], #Customers_DIMAIN.[ClosedDate], #Customers_DIMAIN.[CustomerID], #Customers_DIMAIN.[DateOfBirth], #Customers_DIMAIN.[DeactivatedDate], #Customers_DIMAIN.[EmailAddress], #Customers_DIMAIN.[FileName], #Customers_DIMAIN.[Forename], #Customers_DIMAIN.[Gender], #Customers_DIMAIN.[LoadDate], #Customers_DIMAIN.[MarketableByEmail], #Customers_DIMAIN.[MarketableByPaper], #Customers_DIMAIN.[MarketableByPhone], #Customers_DIMAIN.[MarketableBySms], #Customers_DIMAIN.[PostCode], #Customers_DIMAIN.[RegistrationDate], #Customers_DIMAIN.[RewardCustomerID], #Customers_DIMAIN.[Surname], #Customers_DIMAIN.[VirginCustomerID] INTO #Customers FROM #Customers_DIMAIN WHERE #Customers_DIMAIN.[LoadDate] > DATEADD(DAY, -2, GETDATE()) EXCEPT SELECT  [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[BankID], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[ClosedDate], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[DateOfBirth], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[DeactivatedDate], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[EmailAddress], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[Forename], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[Gender], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[MarketableByEmail], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[MarketableByPaper], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[MarketableByPhone], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[MarketableBySms], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[PostCode], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[RegistrationDate], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[RewardCustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[Surname], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[VirginCustomerID] FROM [DIMAIN2].[WH_Virgin].[Inbound].[Customers] WHERE [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Goodwill') IS NOT NULL DROP TABLE #Goodwill SELECT  #Goodwill_DIMAIN.[CustomerID], #Goodwill_DIMAIN.[FileName], #Goodwill_DIMAIN.[GoodwillAmount], #Goodwill_DIMAIN.[GoodwillDateTime], #Goodwill_DIMAIN.[GoodwillType], #Goodwill_DIMAIN.[LoadDate], #Goodwill_DIMAIN.[VirginCustomerID] INTO #Goodwill FROM #Goodwill_DIMAIN WHERE #Goodwill_DIMAIN.[LoadDate] > DATEADD(DAY, -2, GETDATE()) EXCEPT SELECT  [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[GoodwillAmount], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[GoodwillDateTime], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[GoodwillType], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[VirginCustomerID] FROM [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill] WHERE [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Login') IS NOT NULL DROP TABLE #Login SELECT  #Login_DIMAIN.[CustomerID], #Login_DIMAIN.[FileName], #Login_DIMAIN.[LoadDate], #Login_DIMAIN.[LoginDateTime], #Login_DIMAIN.[LoginInformation], #Login_DIMAIN.[VirginCustomerID] INTO #Login FROM #Login_DIMAIN WHERE #Login_DIMAIN.[LoadDate] > DATEADD(DAY, -2, GETDATE()) EXCEPT SELECT  [DIMAIN2].[WH_Virgin].[Inbound].[Login].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Login].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Login].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Login].[LoginDateTime], [DIMAIN2].[WH_Virgin].[Inbound].[Login].[LoginInformation], [DIMAIN2].[WH_Virgin].[Inbound].[Login].[VirginCustomerID] FROM [DIMAIN2].[WH_Virgin].[Inbound].[Login] WHERE [DIMAIN2].[WH_Virgin].[Inbound].[Login].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Redemptions') IS NOT NULL DROP TABLE #Redemptions SELECT  #Redemptions_DIMAIN.[Amount], #Redemptions_DIMAIN.[CustomerID], #Redemptions_DIMAIN.[FileName], #Redemptions_DIMAIN.[LoadDate], #Redemptions_DIMAIN.[RedemptionDate], #Redemptions_DIMAIN.[RedemptionType] INTO #Redemptions FROM #Redemptions_DIMAIN WHERE #Redemptions_DIMAIN.[LoadDate] > DATEADD(DAY, -2, GETDATE()) EXCEPT SELECT  [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[Amount], [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[RedemptionDate], [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[RedemptionType] FROM [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions] WHERE [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#Transactions') IS NOT NULL DROP TABLE #Transactions SELECT  #Transactions_DIMAIN.[Amount], #Transactions_DIMAIN.[CardholderPresent], #Transactions_DIMAIN.[CardID], #Transactions_DIMAIN.[CardInputMode], #Transactions_DIMAIN.[CashbackAmount], #Transactions_DIMAIN.[CommissionAmount], #Transactions_DIMAIN.[CurrencyCode], #Transactions_DIMAIN.[FileName], #Transactions_DIMAIN.[LoadDate], #Transactions_DIMAIN.[MerchantClassCode], #Transactions_DIMAIN.[MerchantCountry], #Transactions_DIMAIN.[MerchantID], #Transactions_DIMAIN.[MerchantName], #Transactions_DIMAIN.[OfferID], #Transactions_DIMAIN.[TransactionDate], #Transactions_DIMAIN.[TransactionTime], #Transactions_DIMAIN.[UniqueTransactionID], #Transactions_DIMAIN.[VirginOfferID] INTO #Transactions FROM #Transactions_DIMAIN WHERE #Transactions_DIMAIN.[LoadDate] > DATEADD(DAY, -2, GETDATE()) EXCEPT SELECT  [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[Amount], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CardholderPresent], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CardID], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CardInputMode], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CashbackAmount], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CommissionAmount], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CurrencyCode], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[MerchantClassCode], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[MerchantCountry], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[MerchantID], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[MerchantName], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[OfferID], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[TransactionDate], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[TransactionTime], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[UniqueTransactionID], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[VirginOfferID] FROM [DIMAIN2].[WH_Virgin].[Inbound].[Transactions] WHERE [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[LoadDate] > DATEADD(DAY, -2, GETDATE())
	IF OBJECT_ID('tempdb..#WelcomeIronOfferMembers') IS NOT NULL DROP TABLE #WelcomeIronOfferMembers SELECT  #WelcomeIronOfferMembers_DIMAIN.[EndDate], #WelcomeIronOfferMembers_DIMAIN.[HydraOfferID], #WelcomeIronOfferMembers_DIMAIN.[ImportDate], #WelcomeIronOfferMembers_DIMAIN.[SourceUID], #WelcomeIronOfferMembers_DIMAIN.[StartDate], #WelcomeIronOfferMembers_DIMAIN.[WelcomeIronOfferMembersID] INTO #WelcomeIronOfferMembers FROM #WelcomeIronOfferMembers_DIMAIN WHERE #WelcomeIronOfferMembers_DIMAIN.[ImportDate] > DATEADD(DAY, -2, GETDATE()) EXCEPT SELECT  [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[EndDate], [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[HydraOfferID], [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[ImportDate], [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[SourceUID], [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[StartDate], [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[WelcomeIronOfferMembersID] FROM [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers] WHERE [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[ImportDate] > DATEADD(DAY, -2, GETDATE())

	INSERT INTO [DIMAIN2].[WH_Virgin].[Inbound].[Accounts] ( [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[AccountID], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[AccountRelationship], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[AccountStatus], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[AccountType], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[BankID], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[CashbackNomineeID], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Accounts].[LoadDate]) SELECT  #Accounts.[AccountID], #Accounts.[AccountRelationship], #Accounts.[AccountStatus], #Accounts.[AccountType], #Accounts.[BankID], #Accounts.[CashbackNomineeID], #Accounts.[CustomerID], #Accounts.[FileName], #Accounts.[LoadDate] FROM #Accounts ORDER BY #Accounts.[LoadDate]
	INSERT INTO [DIMAIN2].[WH_Virgin].[Inbound].[Balances] ( [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[CashbackAvailable], [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[CashbackLifeTimeValue], [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[CashbackPending], [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Balances].[LoadDate]) SELECT  #Balances.[CashbackAvailable], #Balances.[CashbackLifeTimeValue], #Balances.[CashbackPending], #Balances.[CustomerID], #Balances.[FileName], #Balances.[LoadDate] FROM #Balances ORDER BY #Balances.[LoadDate]
	INSERT INTO [DIMAIN2].[WH_Virgin].[Inbound].[Cards] ( [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[AccountID], [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[BankID], [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[CardID], [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Cards].[PrimaryCustomerID]) SELECT  #Cards.[AccountID], #Cards.[BankID], #Cards.[CardID], #Cards.[FileName], #Cards.[LoadDate], #Cards.[PrimaryCustomerID] FROM #Cards ORDER BY #Cards.[LoadDate]
	INSERT INTO [DIMAIN2].[WH_Virgin].[Inbound].[Customers] ( [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[BankID], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[ClosedDate], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[DateOfBirth], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[DeactivatedDate], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[EmailAddress], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[Forename], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[Gender], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[MarketableByEmail], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[MarketableByPaper], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[MarketableByPhone], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[MarketableBySms], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[PostCode], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[RegistrationDate], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[RewardCustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[Surname], [DIMAIN2].[WH_Virgin].[Inbound].[Customers].[VirginCustomerID]) SELECT  #Customers.[BankID], #Customers.[ClosedDate], #Customers.[CustomerID], #Customers.[DateOfBirth], #Customers.[DeactivatedDate], #Customers.[EmailAddress], #Customers.[FileName], #Customers.[Forename], #Customers.[Gender], #Customers.[LoadDate], #Customers.[MarketableByEmail], #Customers.[MarketableByPaper], #Customers.[MarketableByPhone], #Customers.[MarketableBySms], #Customers.[PostCode], #Customers.[RegistrationDate], #Customers.[RewardCustomerID], #Customers.[Surname], #Customers.[VirginCustomerID] FROM #Customers ORDER BY #Customers.[LoadDate]
	INSERT INTO [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill] ( [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[GoodwillAmount], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[GoodwillDateTime], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[GoodwillType], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Goodwill].[VirginCustomerID]) SELECT  #Goodwill.[CustomerID], #Goodwill.[FileName], #Goodwill.[GoodwillAmount], #Goodwill.[GoodwillDateTime], #Goodwill.[GoodwillType], #Goodwill.[LoadDate], #Goodwill.[VirginCustomerID] FROM #Goodwill ORDER BY #Goodwill.[LoadDate]
	INSERT INTO [DIMAIN2].[WH_Virgin].[Inbound].[Login] ( [DIMAIN2].[WH_Virgin].[Inbound].[Login].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Login].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Login].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Login].[LoginDateTime], [DIMAIN2].[WH_Virgin].[Inbound].[Login].[LoginInformation], [DIMAIN2].[WH_Virgin].[Inbound].[Login].[VirginCustomerID]) SELECT  #Login.[CustomerID], #Login.[FileName], #Login.[LoadDate], #Login.[LoginDateTime], #Login.[LoginInformation], #Login.[VirginCustomerID] FROM #Login ORDER BY #Login.[LoadDate]
	INSERT INTO [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions] ( [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[Amount], [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[CustomerID], [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[RedemptionDate], [DIMAIN2].[WH_Virgin].[Inbound].[Redemptions].[RedemptionType]) SELECT  #Redemptions.[Amount], #Redemptions.[CustomerID], #Redemptions.[FileName], #Redemptions.[LoadDate], #Redemptions.[RedemptionDate], #Redemptions.[RedemptionType] FROM #Redemptions ORDER BY #Redemptions.[LoadDate]
	INSERT INTO [DIMAIN2].[WH_Virgin].[Inbound].[Transactions] ( [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[Amount], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CardholderPresent], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CardID], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CardInputMode], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CashbackAmount], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CommissionAmount], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[CurrencyCode], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[FileName], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[LoadDate], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[MerchantClassCode], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[MerchantCountry], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[MerchantID], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[MerchantName], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[OfferID], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[TransactionDate], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[TransactionTime], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[UniqueTransactionID], [DIMAIN2].[WH_Virgin].[Inbound].[Transactions].[VirginOfferID]) SELECT  #Transactions.[Amount], #Transactions.[CardholderPresent], #Transactions.[CardID], #Transactions.[CardInputMode], #Transactions.[CashbackAmount], #Transactions.[CommissionAmount], #Transactions.[CurrencyCode], #Transactions.[FileName], #Transactions.[LoadDate], #Transactions.[MerchantClassCode], #Transactions.[MerchantCountry], #Transactions.[MerchantID], #Transactions.[MerchantName], #Transactions.[OfferID], #Transactions.[TransactionDate], #Transactions.[TransactionTime], #Transactions.[UniqueTransactionID], #Transactions.[VirginOfferID] FROM #Transactions ORDER BY #Transactions.[LoadDate]
	
	SET IDENTITY_INSERT [WH_Virgin].[Inbound].[WelcomeIronOfferMembers] ON
	INSERT INTO [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers] ( [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[EndDate], [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[HydraOfferID], [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[ImportDate], [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[SourceUID], [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[StartDate], [DIMAIN2].[WH_Virgin].[Inbound].[WelcomeIronOfferMembers].[WelcomeIronOfferMembersID]) SELECT  #WelcomeIronOfferMembers.[EndDate], #WelcomeIronOfferMembers.[HydraOfferID], #WelcomeIronOfferMembers.[ImportDate], #WelcomeIronOfferMembers.[SourceUID], #WelcomeIronOfferMembers.[StartDate], #WelcomeIronOfferMembers.[WelcomeIronOfferMembersID] FROM #WelcomeIronOfferMembers ORDER BY #WelcomeIronOfferMembers.[ImportDate]
	SET IDENTITY_INSERT [WH_Virgin].[Inbound].[WelcomeIronOfferMembers] OFF

END




