CREATE TABLE [Zoe].[EONDataImport_20200818_v2] (
    [ID]                        BIGINT       NULL,
    [ACCOUNT_NAME]              VARCHAR (50) NULL,
    [CUSTOMER_FIRST_NAME]       VARCHAR (50) NULL,
    [CUSTOMER_LAST_NAME]        VARCHAR (50) NULL,
    [CUSTOMER_EMAIL_ADDRESS]    VARCHAR (50) NULL,
    [CUSTOMER_POSTAL_ADDRESS_1] VARCHAR (50) NULL,
    [CUSTOMER_POSTCODE]         VARCHAR (50) NULL,
    [ELEC_PRODUCT_GROUP]        VARCHAR (50) NULL,
    [ELEC_PRODUCT_DESC]         VARCHAR (50) NULL,
    [GAS_PRODUCT_GROUP]         VARCHAR (50) NULL,
    [GAS_PRODUCT_DESC]          VARCHAR (50) NULL,
    [SALES_CHANNEL]             VARCHAR (50) NULL,
    [FUEL_MIX]                  VARCHAR (50) NULL
);

