CREATE TABLE [dbo].[SFDDailyDataLog] (
    [ID]             INT      IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CompletionDate] DATETIME NOT NULL,
    CONSTRAINT [PK_SFDDailyDataLog] PRIMARY KEY CLUSTERED ([ID] ASC)
);

