CREATE TABLE [MIDI].[CTLoad_MIDIHolding] (
    [FileID]                 INT              NOT NULL,
    [RowNum]                 BIGINT           NOT NULL,
    [FileName]               NVARCHAR (100)   NULL,
    [LoadDate]               DATETIME2 (7)    NULL,
    [CardID]                 UNIQUEIDENTIFIER NULL,
    [BankID]                 INT              NULL,
    [CIN]                    VARCHAR (50)     NULL,
    [CINID]                  BIGINT           NULL,
    [MID]                    VARCHAR (100)    NULL,
    [MerchantCountry]        VARCHAR (100)    NULL,
    [LocationID]             BIGINT           NULL,
    [LocationAddress]        VARCHAR (100)    NULL,
    [MerchantName]           NVARCHAR (200)   NULL,
    [CardholderPresentData]  VARCHAR (50)     NULL,
    [MCC]                    VARCHAR (50)     NULL,
    [MCCID]                  INT              NULL,
    [TranDate]               DATETIME2 (0)    NOT NULL,
    [Amount]                 MONEY            NULL,
    [CurrencyCode]           VARCHAR (50)     NULL,
    [CardInputMode]          VARCHAR (50)     NULL,
    [InputModeID]            INT              NULL,
    [PaymentTypeID]          INT              NULL,
    [CashbackAmount]         MONEY            NULL,
    [IsOnline]               BIT              NULL,
    [IsRefund]               BIT              NULL,
    [ConsumerCombinationID]  INT              NULL,
    [RequiresSecondaryID]    BIT              CONSTRAINT [DF_Staging_CTLoad_MIDIHolding_RF] DEFAULT ((0)) NULL,
    [SecondaryCombinationID] INT              NULL,
    CONSTRAINT [PK_Staging_CTLoad_MIDIHolding_RF] PRIMARY KEY CLUSTERED ([FileID] ASC, [RowNum] ASC)
);

