CREATE TABLE [Stratification].[CBPCardUsageUplift_AdjustmentFactor_byCohort] (
    [Label]                    VARCHAR (50) NOT NULL,
    [MonthID]                  INT          NOT NULL,
    [ActivatedCount]           INT          NULL,
    [ControlCount]             INT          NULL,
    [ActivatedSpenders]        INT          NULL,
    [ControlSpenders]          INT          NULL,
    [PrePeriodActivatedSales]  FLOAT (53)   NULL,
    [PrePeriodControlSales]    FLOAT (53)   NULL,
    [AdjFactor_TotalSPC]       FLOAT (53)   NULL,
    [AdjFactor_TotalRR]        FLOAT (53)   NULL,
    [AdjFactor_TotalSPS]       FLOAT (53)   NULL,
    [AdjFactor_TotalATV]       FLOAT (53)   NULL,
    [AdjFactor_TotalATF]       FLOAT (53)   NULL,
    [AdjFactor_EligibleSPC]    FLOAT (53)   NULL,
    [AdjFactor_EligibleRR]     FLOAT (53)   NULL,
    [AdjFactor_EligibleSPS]    FLOAT (53)   NULL,
    [AdjFactor_EligibleATV]    FLOAT (53)   NULL,
    [AdjFactor_EligibleATF]    FLOAT (53)   NULL,
    [AdjFactor_NonEligibleSPC] FLOAT (53)   NULL,
    [AdjFactor_NonEligibleRR]  FLOAT (53)   NULL,
    [AdjFactor_NonEligibleSPS] FLOAT (53)   NULL,
    [AdjFactor_NonEligibleATV] FLOAT (53)   NULL,
    [AdjFactor_NonEligibleATF] FLOAT (53)   NULL
);

