CREATE TABLE [WHB].[Customer] (
    [CustomerGUID]        UNIQUEIDENTIFIER NULL,
    [FanID]               INT              NOT NULL,
    [ClubID]              INT              NULL,
    [CompositeID]         BIGINT           NULL,
    [SourceUID]           VARCHAR (64)     NULL,
    [AccountType]         VARCHAR (20)     NULL,
    [Email]               VARCHAR (100)    NULL,
    [EmailStructureValid] BIT              NULL,
    [MobileTelephone]     NVARCHAR (50)    NULL,
    [Title]               VARCHAR (20)     NULL,
    [FirstName]           VARCHAR (100)    NULL,
    [LastName]            VARCHAR (100)    NULL,
    [Address1]            VARCHAR (100)    NULL,
    [Address2]            VARCHAR (100)    NULL,
    [City]                VARCHAR (100)    NULL,
    [County]              VARCHAR (100)    NULL,
    [PostCode]            VARCHAR (100)    NULL,
    [Region]              VARCHAR (30)     NULL,
    [PostalSector]        VARCHAR (6)      NULL,
    [PostCodeDistrict]    VARCHAR (4)      NULL,
    [PostArea]            VARCHAR (2)      NULL,
    [CAMEOCode]           VARCHAR (10)     NULL,
    [Gender]              CHAR (1)         NULL,
    [DOB]                 DATE             NULL,
    [AgeCurrent]          TINYINT          NULL,
    [AgeCurrentBandText]  VARCHAR (10)     NULL,
    [CashbackPending]     MONEY            NOT NULL,
    [CashbackAvailable]   MONEY            NOT NULL,
    [CashbackLTV]         MONEY            NOT NULL,
    [Unsubscribed]        BIT              NULL,
    [Hardbounced]         BIT              NULL,
    [MarketableByEmail]   BIT              NULL,
    [EmailTracking]       BIT              NULL,
    [MarketableByPush]    BIT              NULL,
    [CurrentlyActive]     BIT              NULL,
    [RegistrationDate]    DATE             NULL,
    [ClosedDate]          DATE             NULL,
    [DeactivatedDate]     DATE             NULL,
    CONSTRAINT [PK_Customer_FanID] PRIMARY KEY CLUSTERED ([FanID] ASC) WITH (FILLFACTOR = 75)
);

