  CREATE VIEW [dbo].[hydra_offerwebassetcollateral]
AS
SELECT [offerwebassetcollateralid]
      ,[offerid]
      ,[bannertitle]
      ,[logo]
      ,[logothumbnail]
      ,[longcopy]
      ,[marketingratedisplaytext]
      ,[offerheader]
      ,[prioritisationscore]
      ,[shortcopy]
      ,[websiteurldisplaytext]
      ,[websiteurllink]
      ,[createddate]
      ,[modifieddate]
      ,[deleteddate]
      ,[deleted]
      ,[carouselbackground]
      ,[carousellogo]
  FROM SLC_Snapshot.[dbo].[hydra_offerwebassetcollateral]