  CREATE VIEW [dbo].[hydra_offeremailassetcollateral]
AS
SELECT  [offeremailassetcollateralid]
      ,[offerid]
      ,[calltoactionurl]
      ,[emailcopy]
      ,[emailofferheader]
      ,[emailmarketingratedisplaytext]
      ,[logo]
      ,[logothumbnail]
      ,[logourl]
      ,[createddate]
      ,[modifieddate]
      ,[deleteddate]
      ,[deleted]
  FROM SLC_Snapshot.[dbo].[hydra_offeremailassetcollateral]