CREATE TABLE [Processing].[QA_Masking_SpotCheck] (
    [ConsumerCombinationID]                INT           NOT NULL,
    [BrandMIDID]                           INT           NULL,
    [BrandID]                              SMALLINT      NOT NULL,
    [MID]                                  VARCHAR (50)  NOT NULL,
    [Narrative]                            VARCHAR (50)  NOT NULL,
    [LocationCountry]                      VARCHAR (3)   NOT NULL,
    [MCCID]                                SMALLINT      NOT NULL,
    [OriginatorID]                         VARCHAR (11)  NOT NULL,
    [IsHighVariance]                       BIT           NOT NULL,
    [IsUKSpend]                            BIT           NOT NULL,
    [PaymentGatewayStatusID]               TINYINT       NOT NULL,
    [IsCreditOrigin]                       BIT           NOT NULL,
    [MerchantZip]                          VARCHAR (50)  NULL,
    [MCC]                                  VARCHAR (50)  NULL,
    [BrandName]                            VARCHAR (50)  NULL,
    [LocationAddress]                      VARCHAR (50)  NULL,
    [RowNum]                               INT           NULL,
    [ProxyMIDTupleID]                      BINARY (32)   NOT NULL,
    [ProxyMID]                             VARCHAR (MAX) NOT NULL,
    [MaskedNarrative]                      VARCHAR (50)  NULL,
    [isBlanketMasked]                      BIT           NOT NULL,
    [isSensitiveMasked]                    BIT           NOT NULL,
    [isHeavyMasked]                        BIT           NOT NULL,
    [isLightMasked]                        BIT           NOT NULL,
    [isGB]                                 BIT           NULL,
    [l1m]                                  INT           NULL,
    [l12m]                                 INT           NULL,
    [l5y]                                  INT           NULL,
    [rxm]                                  INT           NULL,
    [isBrandedMID]                         BIT           NULL,
    [isSensitiveNarrative]                 BIT           NULL,
    [isLimitedNarrative]                   BIT           NULL,
    [isOverTransThreshold]                 BIT           NULL,
    [isLightMaskMCC]                       BIT           NULL,
    [isHeavyMaskMCC]                       BIT           NULL,
    [shouldBeCandidateForSensitiveMasking] BIT           NULL,
    [shouldBeCandidateForBlanketMasking]   BIT           NULL,
    [shouldBeCandidateForLightMasking]     BIT           NULL,
    [shouldBeCandidateForHeavyMasking]     BIT           NULL
);

