CREATE TABLE [Processing].[QA_Masking_SpotCheck_Subset] (
    [ID]                                   INT          IDENTITY (1, 1) NOT NULL,
    [shouldBeCandidateForMasking]          BIT          NULL,
    [shouldBeCandidateForSensitiveMasking] BIT          NULL,
    [shouldBeCandidateForBlanketMasking]   BIT          NULL,
    [shouldBeCandidateForHeavyMasking]     BIT          NULL,
    [shouldBeCandidateForLightMasking]     BIT          NULL,
    [BrandName]                            VARCHAR (50) NULL,
    [LocationCountry]                      VARCHAR (3)  NOT NULL,
    [MCC]                                  VARCHAR (50) NULL,
    [Narrative]                            VARCHAR (50) NOT NULL,
    [MaskedNarrative]                      VARCHAR (50) NULL,
    [MID]                                  VARCHAR (50) NOT NULL,
    [L1M_TranCount]                        INT          NULL,
    [L12M_TranCount]                       INT          NULL,
    [L5Y_TranCount]                        INT          NULL,
    [RollingXMonth_TranCount]              INT          NULL,
    [isSensitiveMasked]                    BIT          NOT NULL,
    [isBlanketMasked]                      BIT          NOT NULL,
    [isHeavyMasked]                        BIT          NOT NULL,
    [isLightMasked]                        BIT          NOT NULL,
    [isGB]                                 BIT          NULL,
    [isBrandedMID]                         BIT          NULL,
    [isSensitiveNarrative]                 BIT          NULL,
    [isLimitedNarrative]                   BIT          NULL,
    [isOverTransThreshold]                 BIT          NULL,
    [isHeavyMaskMCC]                       BIT          NULL,
    [isLightMaskMCC]                       BIT          NULL,
    [SubsetType]                           VARCHAR (30) NULL
);

