CREATE LOGIN [JoanneK]
    WITH PASSWORD = N'r6o{veamdmE$texppNcro.v4msFT7_&#$!~<Rhss~zcmggcV', SID = 0xF20985CCED049742B4FF07EA6CA17EF6, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

