CREATE TABLE [ExcelQuery].[CampaignPlanning_Calculations] (
    [ID]                        INT            NOT NULL,
    [Override_rate]             NUMERIC (7, 4) NULL,
    [baserate]                  NUMERIC (7, 4) NULL,
    [c_length]                  DECIMAL (4, 2) NULL,
    [audience_now]              INT            NULL,
    [audience_fcst]             INT            NULL,
    [control_share]             DECIMAL (3, 2) NULL,
    [b_day_share]               FLOAT (53)     NULL,
    [HALO]                      FLOAT (53)     NULL,
    [uplift]                    DECIMAL (5, 4) NULL,
    [season_SPC]                FLOAT (53)     NULL,
    [season_SPS]                FLOAT (53)     NULL,
    [season_RR]                 FLOAT (53)     NULL,
    [Mailed_group]              INT            NULL,
    [Control_Group]             INT            NULL,
    [Total_sales]               MONEY          NULL,
    [Natural_Sales]             MONEY          NULL,
    [Incremental_Sales]         MONEY          NULL,
    [Qualifying_sales]          MONEY          NULL,
    [Cost_of_Campaign]          MONEY          NULL,
    [Incremental_Sales_ROI]     MONEY          NULL,
    [Incremental_sales_ROI_ext] MONEY          NULL,
    [Billing_rate]              DECIMAL (4, 2) NULL,
    [Final_offer_rate]          DECIMAL (4, 2) NULL,
    [ActiveRow]                 BIT            DEFAULT ((0)) NULL,
    [status_startdate]          DATE           NULL,
    [status_enddate]            DATE           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

