CREATE TABLE [Relational].[BookingCal_CustomerSelection] (
    [ID]                       INT           IDENTITY (1, 1) NOT NULL,
    [ClientServicesRef]        VARCHAR (40)  NOT NULL,
    [Campaign_StartDate]       DATE          NULL,
    [Campaign_EndDate]         DATE          NULL,
    [SegmentID]                VARCHAR (6)   NULL,
    [Gender]                   CHAR (1)      NULL,
    [MinAge]                   INT           NULL,
    [MaxAge]                   INT           NULL,
    [DriveTimeBand]            VARCHAR (50)  NULL,
    [CAMEO_CODE_GRP]           VARCHAR (200) NULL,
    [SocialClass]              NVARCHAR (2)  NULL,
    [MinHeatMapScore]          INT           NULL,
    [MaxHeatMapScore]          INT           NULL,
    [BespokeTargeting]         BIT           NOT NULL,
    [QualifyingMids]           BIT           NOT NULL,
    [TargetedVolume]           INT           NULL,
    [ControlVolume]            INT           NULL,
    [TotalSpenders]            INT           NULL,
    [QualifyingSpenders]       INT           NULL,
    [TotalIncrementalSpenders] INT           NULL,
    [TotalSales]               MONEY         NULL,
    [QualifyingSales]          MONEY         NULL,
    [TotalIncrementalSales]    MONEY         NULL,
    [ForecastSubmissionDate]   DATETIME      NULL,
    [RetailerType]             VARCHAR (40)  NULL,
    [Status_StartDate]         DATE          NOT NULL,
    [Status_EndDate]           DATE          NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

