CREATE TABLE [Relational].[MSData] (
    [StoreNumber]          VARCHAR (500) NULL,
    [StoreName]            VARCHAR (500) NULL,
    [CASRegionNumber]      VARCHAR (500) NULL,
    [CASRegionName]        VARCHAR (500) NULL,
    [AdminRegionNumber]    VARCHAR (500) NULL,
    [AdminRegionName]      VARCHAR (500) NULL,
    [CommRegionNumber]     VARCHAR (500) NULL,
    [CommRegionName]       VARCHAR (500) NULL,
    [DivisionNumber]       VARCHAR (500) NULL,
    [DivisionName]         VARCHAR (500) NULL,
    [CountryStoreNo]       VARCHAR (500) NULL,
    [Country]              VARCHAR (500) NULL,
    [TypeofStore1]         VARCHAR (500) NULL,
    [TypeofStore2]         VARCHAR (500) NULL,
    [TypeofStore3]         VARCHAR (500) NULL,
    [StoreAddress]         VARCHAR (500) NULL,
    [TelephoneNumber]      VARCHAR (500) NULL,
    [MandSFSMerchantID]    VARCHAR (500) NULL,
    [DinersMerchantID]     VARCHAR (500) NULL,
    [AmexMerchantID]       VARCHAR (500) NULL,
    [BMSMerchantID]        VARCHAR (500) NULL,
    [HSBCMerchantID]       VARCHAR (500) NULL,
    [STREAMLINEMerchantID] VARCHAR (500) NULL,
    [EmailAddress]         VARCHAR (500) NULL,
    [EnquirySystem]        VARCHAR (500) NULL,
    [Active]               VARCHAR (500) NULL,
    [Column 26]            VARCHAR (500) NULL,
    [Column 27]            VARCHAR (500) NULL
);

