CREATE TABLE [Relational].[SP_WhoIsActiveDelta_Temp] (
    [session_id]               SMALLINT     NOT NULL,
    [blocked_session_count]    VARCHAR (30) NULL,
    [blocking_session_id]      SMALLINT     NULL,
    [context_switches]         VARCHAR (30) NULL,
    [CPU]                      VARCHAR (30) NULL,
    [CPU_delta]                VARCHAR (30) NULL,
    [login_time]               DATETIME     NULL,
    [open_tran_count]          VARCHAR (30) NULL,
    [physical_io]              VARCHAR (30) NULL,
    [physical_reads]           VARCHAR (30) NULL,
    [physical_reads_delta]     VARCHAR (30) NULL,
    [reads]                    VARCHAR (30) NULL,
    [reads_delta]              VARCHAR (30) NULL,
    [request_id]               INT          NULL,
    [start_time]               DATETIME     NOT NULL,
    [tasks]                    VARCHAR (30) NULL,
    [tempdb_allocations]       VARCHAR (30) NULL,
    [tempdb_allocations_delta] VARCHAR (30) NULL,
    [tempdb_current]           VARCHAR (30) NULL,
    [tempdb_current_delta]     VARCHAR (30) NULL,
    [used_memory]              VARCHAR (30) NULL,
    [used_memory_delta]        VARCHAR (30) NULL,
    [writes]                   VARCHAR (30) NULL,
    [writes_delta]             VARCHAR (30) NULL,
    [query_plan]               XML          NULL,
    [sql_text]                 XML          NULL
);

