CREATE TABLE [Inbound].[Visa_Customer] (
    [FanID]               INT              NOT NULL,
    [CustomerGUID]        UNIQUEIDENTIFIER NOT NULL,
    [ClubID]              INT              NULL,
    [CompositeID]         BIGINT           NULL,
    [SourceUID]           VARCHAR (64)     NULL,
    [AccountType]         VARCHAR (20)     NULL,
    [EmailStructureValid] BIT              NULL,
    [Title]               VARCHAR (20)     NULL,
    [City]                VARCHAR (100)    NULL,
    [County]              VARCHAR (100)    NULL,
    [Region]              VARCHAR (30)     NULL,
    [PostalSector]        VARCHAR (6)      NULL,
    [PostCodeDistrict]    VARCHAR (4)      NULL,
    [PostArea]            VARCHAR (2)      NULL,
    [CAMEOCode]           VARCHAR (10)     NULL,
    [Gender]              CHAR (1)         NULL,
    [AgeCurrent]          TINYINT          NULL,
    [AgeCurrentBandText]  VARCHAR (10)     NULL,
    [CashbackPending]     MONEY            NOT NULL,
    [CashbackAvailable]   MONEY            NOT NULL,
    [CashbackLTV]         MONEY            NOT NULL,
    [Unsubscribed]        BIT              NULL,
    [Hardbounced]         BIT              NULL,
    [MarketableByEmail]   BIT              NULL,
    [EmailTracking]       BIT              NULL,
    [MarketableByPush]    BIT              NULL,
    [CurrentlyActive]     BIT              NULL,
    [RegistrationDate]    DATE             NULL,
    [DeactivatedDate]     DATE             NULL
);

