CREATE LOGIN [CRTImport]
    WITH PASSWORD = N'oVvzuounllnos&t{cnaz,ajjmsFT7_&#$!~<ehf{nw=Iu1aj', SID = 0x4CD3B3DDF48D9E42B45FE90C978DE595, DEFAULT_DATABASE = [Archive_Light], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

