CREATE LOGIN [GunayS]
    WITH PASSWORD = N'_iwcyuiPo{tWbgxuuvukjpidmsFT7_&#$!~<jhxypz|klotz', SID = 0xFBD8AF9F827A3442904F93B583C0DD72, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

