CREATE LOGIN [JoanneK]
    WITH PASSWORD = N'=iowcy,ui{foA2o{tQ:wDJ}$msFT7_&#$!~<`Tgxuvkjgpid', SID = 0xF20985CCED049742B4FF07EA6CA17EF6, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

