CREATE LOGIN [Vernon]
    WITH PASSWORD = N'ozu!oullnQorxst.{HcnazjYmsFT7_&#$!~<janeh{jnwu_a', SID = 0xA7FC05F8E37ACB42AAAA8F201E2FF369, DEFAULT_DATABASE = [Sandbox], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

