CREATE LOGIN [VitaliiV]
    WITH PASSWORD = N'iw5cyuSiUo{tgxuvkjpidjlgmsFT7_&#$!~<ihxypz|lz>la', SID = 0x2D08581BA4AA6F4EB3AC7CC76FE6085B, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

