CREATE PROCEDURE [dbo].[MigrationCheck_MIDI_CTLoad_MIDIHolding] AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @RowCount BIGINT

IF 1 = 1 BEGIN
	IF OBJECT_ID('tempdb..#MIDIHoldingDIMAIN2') IS NOT NULL DROP TABLE #MIDIHoldingDIMAIN2;
	SELECT FileID, RowNum, [hash] = CHECKSUM(*) 
	INTO #MIDIHoldingDIMAIN2
	FROM Warehouse.Staging.CTLoad_MIDIHolding
	SET @RowCount = @@ROWCOUNT
	CREATE UNIQUE CLUSTERED INDEX ucx_FileID_RowNum ON #MIDIHoldingDIMAIN2 (FileID, RowNum)
	-- (553015 rows affected) / 00:00:59

	IF OBJECT_ID('tempdb..#MIDIHoldingDIDEVTEST') IS NOT NULL DROP TABLE #MIDIHoldingDIDEVTEST;
	SELECT FileID, RowNum, [hash] 
	INTO #MIDIHoldingDIDEVTEST 
	FROM OPENQUERY (DIDEVTEST, 'SELECT FileID, RowNum, [hash] = CHECKSUM(*) FROM Warehouse.Staging.CTLoad_MIDIHolding')
	CREATE UNIQUE CLUSTERED INDEX ucx_FileID_RowNum ON #MIDIHoldingDIDEVTEST (FileID, RowNum)
	-- (553015 rows affected) / 00:06:05

	IF OBJECT_ID('tempdb..#MIDIHoldingDIMAIN') IS NOT NULL DROP TABLE #MIDIHoldingDIMAIN;
	SELECT FileID, RowNum, [hash] 
	INTO #MIDIHoldingDIMAIN 
	FROM OPENQUERY (DIMAIN, 'SELECT FileID, RowNum, [hash] = CHECKSUM(*) FROM Warehouse.Staging.CTLoad_MIDIHolding')
	CREATE UNIQUE CLUSTERED INDEX ucx_FileID_RowNum ON #MIDIHoldingDIMAIN (FileID, RowNum)
	-- (553015 rows affected) / 00:17:07
END
-- 00:00:12

SELECT TableName = 'Staging.CTLoad_MIDIHolding', [Date] = GETDATE(), [RowCount] = @RowCount

;WITH NewRows AS (
	SELECT [Description] = 'DIDEVTEST-DIMAIN2', [RowCount] = COUNT(*) FROM (SELECT FileID, RowNum FROM #MIDIHoldingDIDEVTEST EXCEPT SELECT FileID, RowNum FROM #MIDIHoldingDIMAIN2) d -- 0
	UNION ALL SELECT 'DIMAIN2-DIDEVTEST', COUNT(*) FROM (SELECT FileID, RowNum FROM #MIDIHoldingDIMAIN2 EXCEPT SELECT FileID, RowNum FROM #MIDIHoldingDIDEVTEST) d -- 0
	UNION ALL
	SELECT 'DIMAIN-DIDEVTEST', COUNT(*) FROM (SELECT FileID, RowNum FROM #MIDIHoldingDIMAIN EXCEPT SELECT FileID, RowNum FROM #MIDIHoldingDIDEVTEST) d -- 0
	UNION ALL SELECT 'DIDEVTEST-DIMAIN', COUNT(*) FROM (SELECT FileID, RowNum FROM #MIDIHoldingDIDEVTEST EXCEPT SELECT FileID, RowNum FROM #MIDIHoldingDIMAIN) d -- 0
	UNION ALL
	SELECT 'DIMAIN2-DIMAIN', COUNT(*) FROM (SELECT FileID, RowNum FROM #MIDIHoldingDIMAIN2 EXCEPT SELECT FileID, RowNum FROM #MIDIHoldingDIMAIN) d -- 0
	UNION ALL SELECT 'DIMAIN-DIMAIN2', COUNT(*) FROM (SELECT FileID, RowNum FROM #MIDIHoldingDIMAIN EXCEPT SELECT FileID, RowNum FROM #MIDIHoldingDIMAIN2) d -- 0
), ChangedRows AS (
	SELECT [Description] = 'DIDEVTEST-DIMAIN2', [RowCount] = COUNT(*) FROM (SELECT * FROM #MIDIHoldingDIDEVTEST EXCEPT SELECT * FROM #MIDIHoldingDIMAIN2) d -- 17
	UNION ALL SELECT 'DIMAIN2-DIDEVTEST', COUNT(*) FROM (SELECT * FROM #MIDIHoldingDIMAIN2 EXCEPT SELECT * FROM #MIDIHoldingDIDEVTEST) d -- 17
	UNION ALL
	SELECT 'DIMAIN-DIDEVTEST', COUNT(*) FROM (SELECT * FROM #MIDIHoldingDIMAIN EXCEPT SELECT * FROM #MIDIHoldingDIDEVTEST) d -- 311
	UNION ALL SELECT 'DIDEVTEST-DIMAIN', COUNT(*) FROM (SELECT * FROM #MIDIHoldingDIDEVTEST EXCEPT SELECT * FROM #MIDIHoldingDIMAIN) d -- 311
	UNION ALL
	SELECT 'DIMAIN2-DIMAIN', COUNT(*) FROM (SELECT * FROM #MIDIHoldingDIMAIN2 EXCEPT SELECT * FROM #MIDIHoldingDIMAIN) d -- 296
	UNION ALL SELECT 'DIMAIN-DIMAIN2', COUNT(*) FROM (SELECT * FROM #MIDIHoldingDIMAIN EXCEPT SELECT * FROM #MIDIHoldingDIMAIN2) d -- 296
)
SELECT n.[Description], n.[RowCount] AS [New rows], c.[RowCount]-n.[RowCount] AS [Changed Rows]
FROM NewRows n
INNER JOIN ChangedRows c 
	ON c.[Description] = n.[Description]
-- 6 / 00:07:17


RETURN 0


