CREATE PROCEDURE [dbo].[MigrationCheck_Check_SchemeTransUniqueID] AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @RowCount BIGINT

IF 1 = 1 BEGIN
	IF OBJECT_ID('tempdb..#DIMAIN2') IS NOT NULL DROP TABLE #DIMAIN2
	SELECT ServerName = 'DIMAIN2', FileID, MatchID = CASE WHEN MatchID IS NULL THEN 'NULL' ELSE 'NOT NULL' END, [RowCount] = COUNT(*) INTO #DIMAIN2 
	FROM Warehouse.MI.SchemeTransUniqueID WHERE FileID > 35186 GROUP BY FileID, CASE WHEN MatchID IS NULL THEN 'NULL' ELSE 'NOT NULL' END
	SET @RowCount = @@ROWCOUNT

	IF OBJECT_ID('tempdb..#DIDEVTEST') IS NOT NULL DROP TABLE #DIDEVTEST
	SELECT ServerName = 'DIDEVTEST', FileID, MatchID = CASE WHEN MatchID IS NULL THEN 'NULL' ELSE 'NOT NULL' END, [RowCount] = COUNT(*) INTO #DIDEVTEST 
	FROM DIDEVTEST.Warehouse.MI.SchemeTransUniqueID WHERE FileID > 35186 GROUP BY FileID, CASE WHEN MatchID IS NULL THEN 'NULL' ELSE 'NOT NULL' END

	IF OBJECT_ID('tempdb..#DIMAIN') IS NOT NULL DROP TABLE #DIMAIN 
	SELECT ServerName = 'DIMAIN', FileID, MatchID = CASE WHEN MatchID IS NULL THEN 'NULL' ELSE 'NOT NULL' END, [RowCount] = COUNT(*) INTO #DIMAIN 
	FROM DIMAIN.Warehouse.MI.SchemeTransUniqueID WHERE FileID > 35186 GROUP BY FileID, CASE WHEN MatchID IS NULL THEN 'NULL' ELSE 'NOT NULL' END
END
-- (107 rows affected) / 00:00:36

SELECT TableName = 'MI.SchemeTransUniqueID', [Date] = GETDATE(), [RowCount] = @RowCount

;WITH Files AS (SELECT DISTINCT FileID FROM (SELECT FileID FROM #DIMAIN2 UNION SELECT FileID FROM #DIDEVTEST UNION SELECT FileID FROM #DIMAIN) d )
SELECT 
	f.FileID,
	x.MatchID,
	DIMAIN2 = d2.[RowCount],
	DIDEVTEST = di.[RowCount],
	DIMAIN = d.[RowCount],
	n.FileType, 
	n.InDate
FROM Files f
CROSS JOIN (SELECT MatchID = 'NOT NULL' UNION ALL SELECT 'NULL') x
LEFT JOIN [SLC_REPL].[dbo].[NobleFiles] n 
	ON n.ID = f.FileID
LEFT JOIN #DIMAIN2 d2 ON d2.FileID = f.FileID AND d2.MatchID = x.MatchID
LEFT JOIN #DIDEVTEST di ON di.FileID = f.FileID AND di.MatchID = x.MatchID
LEFT JOIN #DIMAIN d ON d.FileID = f.FileID AND d.MatchID = x.MatchID
WHERE COALESCE(d2.[RowCount], di.[RowCount], d.[RowCount]) IS NOT NULL
ORDER BY f.FileID DESC, x.MatchID


RETURN 0



