CREATE PROCEDURE [dbo].[MigrationCheck_MIDI_CINList] AS 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @RowCount BIGINT

IF 1 = 1 BEGIN
	IF OBJECT_ID('tempdb..#CINListDIMAIN2') IS NOT NULL DROP TABLE #CINListDIMAIN2;
	SELECT CIN, [hash] = CHECKSUM(*) 
	INTO #CINListDIMAIN2
	FROM Warehouse.relational.CINList
	SET @RowCount = @@ROWCOUNT
	CREATE UNIQUE CLUSTERED INDEX ucx_CIN ON #CINListDIMAIN2 (CIN)
	-- (17856381 rows affected) / 00:00:25

	IF OBJECT_ID('tempdb..#CINListDIDEVTEST') IS NOT NULL DROP TABLE #CINListDIDEVTEST;
	SELECT CIN, [hash] 
	INTO #CINListDIDEVTEST 
	FROM OPENQUERY (DIDEVTEST, 'SELECT CIN, [hash] = CHECKSUM(*) FROM Warehouse.relational.CINList')
	CREATE UNIQUE CLUSTERED INDEX ucx_CIN ON #CINListDIDEVTEST (CIN)
	-- (17856381 rows affected) / 00:00:25

	IF OBJECT_ID('tempdb..#CINListDIMAIN') IS NOT NULL DROP TABLE #CINListDIMAIN;
	SELECT CIN, [hash] 
	INTO #CINListDIMAIN 
	FROM OPENQUERY (DIMAIN, 'SELECT CIN, [hash] = CHECKSUM(*) FROM Warehouse.relational.CINList')
	CREATE UNIQUE CLUSTERED INDEX ucx_CIN ON #CINListDIMAIN (CIN)
	-- (17856381 rows affected) / 00:00:25
END

SELECT TableName = 'Relational.CINList', [Date] = GETDATE(), [RowCount] = @RowCount

;WITH NewRows AS (
	SELECT [Description] = 'DIDEVTEST-DIMAIN2', [RowCount] = COUNT(*) FROM (SELECT CIN FROM #CINListDIDEVTEST EXCEPT SELECT CIN FROM #CINListDIMAIN2) d -- 0
	UNION ALL SELECT 'DIMAIN2-DIDEVTEST', COUNT(*) FROM (SELECT CIN FROM #CINListDIMAIN2 EXCEPT SELECT CIN FROM #CINListDIDEVTEST) d -- 0
	UNION ALL
	SELECT 'DIMAIN-DIDEVTEST', COUNT(*) FROM (SELECT CIN FROM #CINListDIMAIN EXCEPT SELECT CIN FROM #CINListDIDEVTEST) d -- 0
	UNION ALL SELECT 'DIDEVTEST-DIMAIN', COUNT(*) FROM (SELECT CIN FROM #CINListDIDEVTEST EXCEPT SELECT CIN FROM #CINListDIMAIN) d -- 0
	UNION ALL
	SELECT 'DIMAIN2-DIMAIN', COUNT(*) FROM (SELECT CIN FROM #CINListDIMAIN2 EXCEPT SELECT CIN FROM #CINListDIMAIN) d -- 0
	UNION ALL SELECT 'DIMAIN-DIMAIN2', COUNT(*) FROM (SELECT CIN FROM #CINListDIMAIN EXCEPT SELECT CIN FROM #CINListDIMAIN2) d -- 0
), ChangedRows AS (
	SELECT [Description] = 'DIDEVTEST-DIMAIN2', [RowCount] = COUNT(*) FROM (SELECT * FROM #CINListDIDEVTEST EXCEPT SELECT * FROM #CINListDIMAIN2) d -- 17
	UNION ALL SELECT 'DIMAIN2-DIDEVTEST', COUNT(*) FROM (SELECT * FROM #CINListDIMAIN2 EXCEPT SELECT * FROM #CINListDIDEVTEST) d -- 17
	UNION ALL
	SELECT 'DIMAIN-DIDEVTEST', COUNT(*) FROM (SELECT * FROM #CINListDIMAIN EXCEPT SELECT * FROM #CINListDIDEVTEST) d -- 311
	UNION ALL SELECT 'DIDEVTEST-DIMAIN', COUNT(*) FROM (SELECT * FROM #CINListDIDEVTEST EXCEPT SELECT * FROM #CINListDIMAIN) d -- 311
	UNION ALL
	SELECT 'DIMAIN2-DIMAIN', COUNT(*) FROM (SELECT * FROM #CINListDIMAIN2 EXCEPT SELECT * FROM #CINListDIMAIN) d -- 296
	UNION ALL SELECT 'DIMAIN-DIMAIN2', COUNT(*) FROM (SELECT * FROM #CINListDIMAIN EXCEPT SELECT * FROM #CINListDIMAIN2) d -- 296
)
SELECT n.[Description], n.[RowCount] AS [New rows], c.[RowCount]-n.[RowCount] AS [Changed Rows]
FROM NewRows n
INNER JOIN ChangedRows c 
	ON c.[Description] = n.[Description]
-- 6 / 00:01:50


RETURN 0




