CREATE LOGIN [ChrisN]
    WITH PASSWORD = N'|FkGexmshkjp{gfxeucvqjt{msFT7_&#$!~<:jc@;soGx{oe', SID = 0x6AD1D630ABB9644DB9DE848454D93EFE, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

