CREATE LOGIN [ChrisN]
    WITH PASSWORD = N'p>hebekwzc{tc~fyt!whpttjmsFT7_&#$!~<qyjjqnWlQa6D', SID = 0x6AD1D630ABB9644DB9DE848454D93EFE, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

