CREATE LOGIN [JosephS]
    WITH PASSWORD = N'eUxmoxshk3Fjp{gfxucvAqjnmsFT7_&#$!~<eRbt{l,jcsoA', SID = 0xDD7B60DCBE04EF498A54E0FB067EA9F1, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

