CREATE LOGIN [tasfia]
    WITH PASSWORD = N'exmNshkRjpD{gfxucvq&jt{jmsFT7_&#$!~<csCox2I{zXoe', SID = 0x780E25A1C0C324459F54FA31CEA84504, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;


GO
ALTER LOGIN [tasfia] DISABLE;

