CREATE LOGIN [Vernon]
    WITH PASSWORD = N'<GeMpXxm0s8!hkjp{gfxDucvmsFT7_&#$!~<qwjtt{fjcsoT', SID = 0xA7FC05F8E37ACB42AAAA8F201E2FF369, DEFAULT_DATABASE = [Sandbox], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

