CREATE LOGIN [VitaliiV]
    WITH PASSWORD = N'fpv|=s{35krc|wflkmH_tG3nmsFT7_&#$!~<cVp|wuz>kvlr', SID = 0x2D08581BA4AA6F4EB3AC7CC76FE6085B, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

