CREATE TABLE [dbo].[PartnerCommissionRule_OLD] (
    [PartnerCommissionRuleID]           INT           NOT NULL,
    [PartnerID]                         INT           NOT NULL,
    [TypeID]                            INT           NOT NULL,
    [CommissionRate]                    FLOAT (53)    NOT NULL,
    [Status]                            BIT           NOT NULL,
    [Priority]                          INT           NULL,
    [CreationDate]                      DATETIME      NOT NULL,
    [CreationStaffID]                   INT           NOT NULL,
    [DeletionDate]                      DATETIME      NULL,
    [DeletionStaffID]                   INT           NULL,
    [MaximumUsesPerFan]                 INT           NULL,
    [StartDate]                         DATETIME      NULL,
    [EndDate]                           DATETIME      NULL,
    [RequiredNumberOfPriorTransactions] INT           NULL,
    [RequiredMinimumBasketSize]         SMALLMONEY    NULL,
    [RequiredMaximumBasketSize]         SMALLMONEY    NULL,
    [RequiredChannel]                   TINYINT       NULL,
    [RequiredBinRange]                  VARCHAR (6)   NULL,
    [RequiredClubID]                    INT           NULL,
    [RequiredMinimumHourOfDay]          TINYINT       NULL,
    [RequiredMaximumHourOfDay]          TINYINT       NULL,
    [RequiredMerchantID]                VARCHAR (20)  NULL,
    [RequiredIronOfferID]               INT           NULL,
    [RequiredRetailOutletID]            INT           NULL,
    [RequiredCardholderPresence]        TINYINT       NULL,
    [CommissionAmount]                  SMALLMONEY    NULL,
    [CommissionLimit]                   SMALLMONEY    NULL,
    [CreatedDateTime]                   DATETIME2 (7) NOT NULL,
    [UpdatedDateTime]                   DATETIME2 (7) NULL,
    CONSTRAINT [PK_PartnerCommissionRule_OLD] PRIMARY KEY CLUSTERED ([PartnerCommissionRuleID] ASC)
);

