CREATE TABLE [Prototype].[CampaignResults_Aggregate] (
    [GroupedIronOfferID]      INT           NULL,
    [StartDate]               DATE          NULL,
    [EndDate]                 DATE          NULL,
    [SplitName]               NVARCHAR (50) NULL,
    [CashbackRate]            INT           NULL,
    [SpendStretch]            INT           NULL,
    [Cardholders]             INT           NULL,
    [Spenders]                INT           NULL,
    [TotalSales]              MONEY         NULL,
    [Transactions]            INT           NULL,
    [CampaignCost]            MONEY         NULL,
    [PValueSPC]               REAL          NULL,
    [IncrementalSales]        FLOAT (53)    NULL,
    [IncrementalSpendErs]     FLOAT (53)    NULL,
    [IncrementalTransactions] FLOAT (53)    NULL,
    [TotalPValue]             REAL          NULL,
    [PartnerID]               INT           NULL,
    [Uplift]                  REAL          NULL,
    [SpendersUplift]          REAL          NULL,
    [ATVUplift]               REAL          NULL,
    [ATFUplift]               REAL          NULL,
    [PartnerName]             VARCHAR (100) NULL
);

