CREATE TABLE [Prototype].[MTR_Test] (
    [F1]  NVARCHAR (MAX) NULL,
    [F2]  NVARCHAR (MAX) NULL,
    [F3]  NVARCHAR (MAX) NULL,
    [F4]  NVARCHAR (MAX) NULL,
    [F5]  NVARCHAR (MAX) NULL,
    [F6]  NVARCHAR (MAX) NULL,
    [F7]  NVARCHAR (MAX) NULL,
    [F8]  NVARCHAR (MAX) NULL,
    [F9]  NVARCHAR (MAX) NULL,
    [F10] NVARCHAR (MAX) NULL,
    [F11] NVARCHAR (MAX) NULL,
    [F12] NVARCHAR (MAX) NULL,
    [F13] NVARCHAR (MAX) NULL,
    [F14] NVARCHAR (MAX) NULL,
    [F15] NVARCHAR (MAX) NULL,
    [F16] NVARCHAR (MAX) NULL,
    [F17] NVARCHAR (MAX) NULL,
    [F18] NVARCHAR (MAX) NULL,
    [F19] NVARCHAR (MAX) NULL,
    [F20] NVARCHAR (MAX) NULL
);

