CREATE TABLE [dbo].[PartnerStatus] (
    [ID]   SMALLINT      NOT NULL,
    [Name] NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_PartnerStatus] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 95)
);

