CREATE TABLE [dbo].[IndexFragmentation] (
    [id]                           INT           IDENTITY (1, 1) NOT NULL,
    [DateCollected]                DATETIME      NOT NULL,
    [DateStarted]                  DATETIME      NULL,
    [DateFinished]                 DATETIME      NULL,
    [databaseid]                   SMALLINT      NOT NULL,
    [databasename]                 [sysname]     NOT NULL,
    [schemaid]                     INT           NOT NULL,
    [schemaname]                   [sysname]     NOT NULL,
    [Tableid]                      INT           NOT NULL,
    [Tablename]                    [sysname]     NOT NULL,
    [indexid]                      INT           NOT NULL,
    [indexname]                    [sysname]     NULL,
    [partition_number]             INT           NOT NULL,
    [index_type_desc]              NVARCHAR (60) NOT NULL,
    [alloc_unit_type_desc]         NVARCHAR (60) NOT NULL,
    [index_depth]                  TINYINT       NOT NULL,
    [index_level]                  TINYINT       NOT NULL,
    [avg_fragmentation_in_percent] FLOAT (53)    NOT NULL,
    [fragment_count]               BIGINT        NULL,
    [avg_fragment_size_in_pages]   FLOAT (53)    NULL,
    [page_count]                   BIGINT        NOT NULL,
    [allowpagelocks]               BIT           NOT NULL,
    [ActionNote]                   VARCHAR (256) NULL,
    [Usage]                        BIGINT        NULL,
    [LastAccess]                   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

