CREATE PROCEDURE ResetAnalystSecurity

AS

GRANT SELECT, UPDATE, INSERT, DELETE on SCHEMA::dbo to [Analyst]
GRANT SELECT, UPDATE, INSERT, DELETE on SCHEMA::lion to [Analyst]
GRANT SELECT, UPDATE, INSERT, DELETE on SCHEMA::RAS to [Analyst]
GRANT SELECT, UPDATE, INSERT, DELETE on SCHEMA::Redemption to [Analyst]
GRANT SELECT, UPDATE, INSERT, DELETE on SCHEMA::zion to [Analyst]

RETURN 0