CREATE LOGIN [CRTImport]
    WITH PASSWORD = N'zdjFimhpfZS9!#uz4zaypooUmsFT7_&#$!~<gmfdotscYvcB', SID = 0x4CD3B3DDF48D9E42B45FE90C978DE595, DEFAULT_DATABASE = [Archive_Light], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

