CREATE LOGIN [JosephS]
    WITH PASSWORD = N'ro},teQzgzvZyt?qgmxuSo&+msFT7_&#$!~<aioenF{ejlyd', SID = 0xDD7B60DCBE04EF498A54E0FB067EA9F1, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

