CREATE LOGIN [Rory]
    WITH PASSWORD = N'BzdmhjtimhspuzzagmfWtdoTmsFT7_&#$!~<6tKscv1cpm{j', SID = 0xA739BFF0B7C47F4E9D76824FC9AA3EE3, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

