CREATE LOGIN [SamW]
    WITH PASSWORD = N'<zRdC&jimhV0puzhzaYgmkfdmsFT7_&#$!~<otM&scvcpVmu', SID = 0xECCB540E84870A469390DF4128AED5DA, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

