CREATE LOGIN [Rory]
    WITH PASSWORD = N'k,eoghzm|jVomQhe|Wx|okgkmsFT7_&#$!~<|y.%QJXplm!m', SID = 0xA739BFF0B7C47F4E9D76824FC9AA3EE3, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

