CREATE TABLE [ChrisN].[eondata2] (
    [ID]                        BIGINT        NULL,
    [ACCOUNT_NAME]              VARCHAR (100) NULL,
    [CUSTOMER_FIRST_NAME]       VARCHAR (100) NULL,
    [CUSTOMER_LAST_NAME]        VARCHAR (100) NULL,
    [CUSTOMER_EMAIL_ADDRESS]    VARCHAR (100) NULL,
    [CUSTOMER_POSTAL_ADDRESS_1] VARCHAR (100) NULL,
    [CUSTOMER_POSTCODE]         VARCHAR (100) NULL,
    [ELEC_PRODUCT_GROUP]        VARCHAR (100) NULL,
    [ELEC_PRODUCT_DESC]         VARCHAR (100) NULL,
    [GAS_PRODUCT_GROUP]         VARCHAR (100) NULL,
    [GAS_PRODUCT_DESC]          VARCHAR (100) NULL,
    [SALES_CHANNEL]             VARCHAR (100) NULL,
    [FUEL_MIX]                  VARCHAR (100) NULL
);

