CREATE LOGIN [ChrisN]
    WITH PASSWORD = N'bkjJzjcWv{oeuw%v<ynkZdrTmsFT7_&#$!~<qndXgmE0uuxo', SID = 0x6AD1D630ABB9644DB9DE848454D93EFE, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

