CREATE LOGIN [VitaliiV]
    WITH PASSWORD = N'zwwouiRcdfs~bqjxqvs2w+zlmsFT7_&#$!~<d{vlsptHuu|o', SID = 0x2D08581BA4AA6F4EB3AC7CC76FE6085B, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

