CREATE TABLE [dbo].[Club] (
    [ID]                                    INT              NOT NULL,
    [Name]                                  NVARCHAR (100)   NOT NULL,
    [Nickname]                              NVARCHAR (50)    NULL,
    [Abbreviation]                          NVARCHAR (12)    NOT NULL,
    [FolderName]                            NVARCHAR (50)    NOT NULL,
    [Status]                                TINYINT          NOT NULL,
    [AccountNumberPrefix]                   INT              NOT NULL,
    [LastAccountNumber]                     INT              NOT NULL,
    [LastCallCentreCardNumber]              INT              NOT NULL,
    [Pointsname]                            NVARCHAR (50)    NOT NULL,
    [DataAName]                             NVARCHAR (50)    NOT NULL,
    [DataBName]                             NVARCHAR (50)    NOT NULL,
    [DataCName]                             NVARCHAR (50)    NOT NULL,
    [username]                              NVARCHAR (50)    NOT NULL,
    [password]                              NVARCHAR (20)    NOT NULL,
    [sessionid]                             NVARCHAR (50)    NOT NULL,
    [ContactEmail]                          NVARCHAR (50)    NOT NULL,
    [DGMID]                                 NVARCHAR (50)    NOT NULL,
    [DGMPassword]                           NVARCHAR (20)    NOT NULL,
    [EditDetailsPoints]                     INT              NOT NULL,
    [PointsPerPound]                        INT              NOT NULL,
    [ClubSplit]                             FLOAT (53)       NOT NULL,
    [FanSplit]                              FLOAT (53)       NOT NULL,
    [BaseVATID]                             INT              NOT NULL,
    [FirstSwipePoints]                      INT              NOT NULL,
    [FirstSwipeSpendMinimum]                SMALLMONEY       NOT NULL,
    [InitialFanCount]                       INT              NOT NULL,
    [InitialGoneawayCount]                  INT              NOT NULL,
    [InitialDeceasedCount]                  INT              NOT NULL,
    [EmailFromName]                         NVARCHAR (80)    NOT NULL,
    [OnlineLaunchDate]                      DATETIME         NULL,
    [OfflineLaunchDate]                     DATETIME         NULL,
    [Trial]                                 BIT              NULL,
    [ClubUrl]                               NVARCHAR (100)   NULL,
    [OnlineOnly]                            BIT              NOT NULL,
    [RewardUrl]                             NVARCHAR (100)   NULL,
    [AdvancePoints]                         BIT              NOT NULL,
    [ReferralPoints]                        INT              NOT NULL,
    [IsProxy]                               BIT              NOT NULL,
    [ShowVouchers]                          BIT              NOT NULL,
    [ShowScratchCards]                      BIT              NOT NULL,
    [IsCardRegistrationMandatory]           BIT              NOT NULL,
    [MaximumPTPR]                           INT              NOT NULL,
    [ColourPrimary]                         NVARCHAR (7)     NOT NULL,
    [DefaultCountry]                        NVARCHAR (50)    NOT NULL,
    [RegistrationEnabled]                   BIT              NOT NULL,
    [ReferAFanEnabled]                      BIT              NOT NULL,
    [FirstSpendBonus]                       INT              NOT NULL,
    [MinimumAge]                            TINYINT          NOT NULL,
    [BankAccountEnabled]                    BIT              NOT NULL,
    [RedemptionOrderEmail]                  NVARCHAR (50)    NULL,
    [DefaultLanguage]                       NVARCHAR (2)     NOT NULL,
    [Languages]                             NVARCHAR (100)   NOT NULL,
    [RewardsPerPage]                        INT              NOT NULL,
    [OnlinePartnersPerPage]                 INT              NOT NULL,
    [DefaultShoppingCountryID]              INT              NULL,
    [CardRegistrationBonus]                 INT              NULL,
    [RewardShowcaseEnabled]                 BIT              NOT NULL,
    [SignedOutRewardsShowcaseEnabled]       BIT              NOT NULL,
    [SignedInRewardsShowcaseEnabled]        BIT              NOT NULL,
    [ClubTypeID]                            INT              NOT NULL,
    [HomeNotSignedInShowcaseEnabled]        BIT              NOT NULL,
    [RewardsEnabled]                        BIT              NOT NULL,
    [ClubCash]                              BIT              NOT NULL,
    [PrepayProviderID]                      INT              NOT NULL,
    [IncludeInEmailUpload]                  BIT              NOT NULL,
    [SignedInOnlineShoppingShowcaseEnabled] BIT              NOT NULL,
    [RssUrl]                                NVARCHAR (2048)  NOT NULL,
    [GoogleAnalyticsId]                     NVARCHAR (16)    NOT NULL,
    [DefaultCurrency]                       NVARCHAR (1)     NOT NULL,
    [ClubCashName]                          NVARCHAR (20)    NOT NULL,
    [GiftcardsEnabled]                      BIT              NOT NULL,
    [CashCardEnabled]                       BIT              NOT NULL,
    [CashCardMinThreshold]                  SMALLMONEY       NOT NULL,
    [CashCardMaxThreshold]                  SMALLMONEY       NOT NULL,
    [CashCardAllowDebitCards]               BIT              NOT NULL,
    [CashCardAllowCreditCards]              BIT              NOT NULL,
    [AutoEmailEnabled]                      BIT              NOT NULL,
    [CashCardDayLimit]                      SMALLMONEY       NULL,
    [ForcePasswordEnabled]                  BIT              NULL,
    [AutoRedeemEnabled]                     BIT              NULL,
    [DefaultAutoRedeemID]                   INT              NULL,
    [eVoucherDayLimit]                      SMALLMONEY       NULL,
    [ProgrammeUID]                          UNIQUEIDENTIFIER NOT NULL,
    [IsOfferBased]                          BIT              NOT NULL,
    [APISecretKey]                          UNIQUEIDENTIFIER NULL,
    [AllowPublisherToUpdateBalance]         BIT              NOT NULL,
    [LogOutRedirectUrl]                     NVARCHAR (1024)  NULL,
    CONSTRAINT [PK_Club] PRIMARY KEY CLUSTERED ([ID] ASC)
);

