CREATE TABLE [dbo].[MissingTransaction] (
    [ID]                     INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [FanID]                  INT             NOT NULL,
    [ClubId]                 INT             NULL,
    [DateReported]           DATETIME        NOT NULL,
    [DatePurchased]          DATETIME        NOT NULL,
    [DateDelivered]          DATETIME        NULL,
    [OutletName]             NVARCHAR (100)  NULL,
    [OutletLocation]         NVARCHAR (100)  NULL,
    [WhyPointsAreExpected]   NVARCHAR (100)  NULL,
    [SpendAmount]            SMALLMONEY      NOT NULL,
    [PointsExpected]         INT             NOT NULL,
    [PointsAwarded]          INT             NULL,
    [ClubCashExpected]       SMALLMONEY      NOT NULL,
    [ClubCashAwarded]        SMALLMONEY      NULL,
    [InternetSecurityLevel]  NVARCHAR (100)  NOT NULL,
    [InternetPrivacyLevel]   NVARCHAR (100)  NOT NULL,
    [OrderRefenceNumber]     NVARCHAR (100)  NOT NULL,
    [ItemDescription]        NVARCHAR (100)  NOT NULL,
    [FurtherInformation]     NVARCHAR (2000) NOT NULL,
    [PanID]                  INT             NULL,
    [ReceiptNumber]          NVARCHAR (30)   NULL,
    [MissingTransactionType] INT             NULL,
    [IsAccepted]             BIT             NULL,
    [IsDeclined]             BIT             NULL,
    [Reason]                 NVARCHAR (2000) NULL,
    [EmailSent]              BIT             NULL,
    [PendingTransID]         INT             NULL,
    [ContactNumber]          NVARCHAR (50)   NULL,
    [TransactionMethod]      TINYINT         NULL,
    CONSTRAINT [PK_MissingTransaction] PRIMARY KEY CLUSTERED ([ID] ASC)
);

