CREATE TABLE [InsightArchive].[brand_correlation_pivot] (
    [CINID]                                  INT NULL,
    [AA]                                     INT NULL,
    [AA Insurance]                           INT NULL,
    [Abellio ScotRail]                       INT NULL,
    [Adidas]                                 INT NULL,
    [Admiral Insurance]                      INT NULL,
    [airbnb]                                 INT NULL,
    [Aldi]                                   INT NULL,
    [AliExpress]                             INT NULL,
    [All Bar One]                            INT NULL,
    [All Saints]                             INT NULL,
    [Allpay]                                 INT NULL,
    [Amazon]                                 INT NULL,
    [Amazon Kindle]                          INT NULL,
    [Ambassador Theatre Group]               INT NULL,
    [American Express]                       INT NULL,
    [American Golf]                          INT NULL,
    [AMF Bowling]                            INT NULL,
    [AMT Coffee]                             INT NULL,
    [Ann Summers]                            INT NULL,
    [APCOA]                                  INT NULL,
    [Apple]                                  INT NULL,
    [Applegreen]                             INT NULL,
    [Appliances Online]                      INT NULL,
    [Aqua MasterCard]                        INT NULL,
    [Argos]                                  INT NULL,
    [Arnold Clark]                           INT NULL,
    [Arriva Trains]                          INT NULL,
    [Asda]                                   INT NULL,
    [Asda Petrol]                            INT NULL,
    [ASK Italian]                            INT NULL,
    [ASOS]                                   INT NULL,
    [Audible]                                INT NULL,
    [Autoglass]                              INT NULL,
    [Aviva]                                  INT NULL,
    [AXA Insurance]                          INT NULL,
    [B&M Retail]                             INT NULL,
    [B&Q]                                    INT NULL,
    [B365]                                   INT NULL,
    [Barburrito]                             INT NULL,
    [Barclaycard]                            INT NULL,
    [Bargain Booze]                          INT NULL,
    [Barnardos]                              INT NULL,
    [Barrhead Travel]                        INT NULL,
    [Be at One]                              INT NULL,
    [Beefeater]                              INT NULL,
    [Bella Italia]                           INT NULL,
    [Betfair]                                INT NULL,
    [BHS]                                    INT NULL,
    [Bills]                                  INT NULL,
    [Blacks]                                 INT NULL,
    [Blue Inc]                               INT NULL,
    [Bobbi Brown]                            INT NULL,
    [Body Shop]                              INT NULL,
    [Bodycare]                               INT NULL,
    [Bonmarche]                              INT NULL,
    [Boohoo.com]                             INT NULL,
    [Booker]                                 INT NULL,
    [Booths]                                 INT NULL,
    [Boots]                                  INT NULL,
    [Boots Opticians]                        INT NULL,
    [Boundary Mill Stores]                   INT NULL,
    [Boux Avenue]                            INT NULL,
    [BP]                                     INT NULL,
    [Brantano]                               INT NULL,
    [Brewers Fayre]                          INT NULL,
    [British Airways]                        INT NULL,
    [British Gas]                            INT NULL,
    [British Heart Foundation]               INT NULL,
    [Browns]                                 INT NULL,
    [BT]                                     INT NULL,
    [Budgens]                                INT NULL,
    [Build a Bear]                           INT NULL,
    [Burger King]                            INT NULL,
    [Burton]                                 INT NULL,
    [Burton and Dorothy Perkins]             INT NULL,
    [Butlins]                                INT NULL,
    [Byron Hamburgers]                       INT NULL,
    [Cafe Rouge]                             INT NULL,
    [Caffe Nero]                             INT NULL,
    [Calendar Club]                          INT NULL,
    [Cancer Research UK]                     INT NULL,
    [Capital One]                            INT NULL,
    [Card Factory]                           INT NULL,
    [Cards Galore]                           INT NULL,
    [Carluccio's]                            INT NULL,
    [Carpetright]                            INT NULL,
    [Carphone Warehouse]                     INT NULL,
    [Castle Pubs]                            INT NULL,
    [Cath Kidston]                           INT NULL,
    [Center Parcs]                           INT NULL,
    [Cex]                                    INT NULL,
    [Charles Tyrwhitt]                       INT NULL,
    [Chef & Brewer]                          INT NULL,
    [Chiquito]                               INT NULL,
    [Churchill Insurance]                    INT NULL,
    [Cineworld]                              INT NULL,
    [Claire's Accessories]                   INT NULL,
    [Clarks]                                 INT NULL,
    [Clas Ohlson]                            INT NULL,
    [Clintons Card Shops]                    INT NULL,
    [Co-operative Food]                      INT NULL,
    [Co-operative Petrol]                    INT NULL,
    [Costa]                                  INT NULL,
    [Costco]                                 INT NULL,
    [Costcutter]                             INT NULL,
    [Cote]                                   INT NULL,
    [Cotswold Outdoor]                       INT NULL,
    [Cotton Traders]                         INT NULL,
    [Credit Expert]                          INT NULL,
    [Cross Country Trains]                   INT NULL,
    [Crown Carveries]                        INT NULL,
    [Cunard]                                 INT NULL,
    [Currys PC World]                        INT NULL,
    [Debenhams]                              INT NULL,
    [Decathlon]                              INT NULL,
    [Deichmann]                              INT NULL,
    [Deliveroo]                              INT NULL,
    [DFS]                                    INT NULL,
    [Direct Line Insurance]                  INT NULL,
    [Disney Store]                           INT NULL,
    [Dixons]                                 INT NULL,
    [Dobbies]                                INT NULL,
    [Dominos Pizza]                          INT NULL,
    [Dorothy Perkins]                        INT NULL,
    [Driving Standards Agency]               INT NULL,
    [Dunelm]                                 INT NULL,
    [DVLA]                                   INT NULL,
    [DW Sports]                              INT NULL,
    [E.On Energy]                            INT NULL,
    [East Midlands Trains]                   INT NULL,
    [East Of England Co-op]                  INT NULL,
    [EasyJet]                                INT NULL,
    [Eat]                                    INT NULL,
    [Ebookers.com]                           INT NULL,
    [Ed's Diner]                             INT NULL,
    [EDF Energy]                             INT NULL,
    [Edinburgh Woollen Mill]                 INT NULL,
    [Ember Inns]                             INT NULL,
    [Empire]                                 INT NULL,
    [Enterprise Rent-A-Car]                  INT NULL,
    [Ernest Jones]                           INT NULL,
    [Esso]                                   INT NULL,
    [Esure Group]                            INT NULL,
    [ETSY.com]                               INT NULL,
    [Euro Car Parts]                         INT NULL,
    [Eurochange]                             INT NULL,
    [Europcar]                               INT NULL,
    [Evans Cycles]                           INT NULL,
    [Everyman Cinema]                        INT NULL,
    [Everything Everywhere]                  INT NULL,
    [Expedia]                                INT NULL,
    [Farm Foods]                             INT NULL,
    [Farmhouse Inns]                         INT NULL,
    [Fat Face]                               INT NULL,
    [Fayre & Square]                         INT NULL,
    [Feather & Black]                        INT NULL,
    [Fenwick]                                INT NULL,
    [Five Guys]                              INT NULL,
    [Flaming Grill]                          INT NULL,
    [Flight Centre]                          INT NULL,
    [FlyBe.com]                              INT NULL,
    [Footasylum]                             INT NULL,
    [Footlocker ]                            INT NULL,
    [Forever 21]                             INT NULL,
    [Frankie & Bennys]                       INT NULL,
    [French Connection]                      INT NULL,
    [Funkypigeon.com]                        INT NULL,
    [GAME]                                   INT NULL,
    [GAP]                                    INT NULL,
    [giffgaff]                               INT NULL,
    [Giraffe]                                INT NULL,
    [Go Outdoors]                            INT NULL,
    [Golden Oak Inns]                        INT NULL,
    [Google]                                 INT NULL,
    [Gourmet Burger]                         INT NULL,
    [Great Western Railway]                  INT NULL,
    [Greater Anglia Trains]                  INT NULL,
    [Green King Local Pub]                   INT NULL,
    [Greggs]                                 INT NULL,
    [Groupon]                                INT NULL,
    [H & M]                                  INT NULL,
    [H.Samuel]                               INT NULL,
    [Halfords]                               INT NULL,
    [Halfords Autocentres]                   INT NULL,
    [Halifax]                                INT NULL,
    [Hamleys]                                INT NULL,
    [Harrods]                                INT NULL,
    [Harvester]                              INT NULL,
    [Harvey Nichols]                         INT NULL,
    [Hastings Direct]                        INT NULL,
    [Heals]                                  INT NULL,
    [Heron Foods]                            INT NULL,
    [Hilton Hotels]                          INT NULL,
    [HM Courts & Tribunals Service]          INT NULL,
    [HM Passport Office]                     INT NULL,
    [HMRC]                                   INT NULL,
    [HMV]                                    INT NULL,
    [Hobbs]                                  INT NULL,
    [Hobbycraft]                             INT NULL,
    [Holiday Extras]                         INT NULL,
    [Holiday Hypermarket]                    INT NULL,
    [Holiday Inn]                            INT NULL,
    [Holland and Barrett]                    INT NULL,
    [Hollister]                              INT NULL,
    [Home Bargains]                          INT NULL,
    [Home Retail Group]                      INT NULL,
    [Homebase]                               INT NULL,
    [Homesense]                              INT NULL,
    [Hotel Chocolat]                         INT NULL,
    [Hotel Ibis]                             INT NULL,
    [Hotter Comfort Concept]                 INT NULL,
    [House of Fraser]                        INT NULL,
    [Hungry Horse]                           INT NULL,
    [Hungry House]                           INT NULL,
    [Iceland]                                INT NULL,
    [IKEA]                                   INT NULL,
    [Interflora]                             INT NULL,
    [Itsu]                                   INT NULL,
    [iTunes]                                 INT NULL,
    [iZettle]                                INT NULL,
    [J D Williams]                           INT NULL,
    [Jack Wills]                             INT NULL,
    [Jamie's Italian]                        INT NULL,
    [JD Sports]                              INT NULL,
    [Jet2 Holidays]                          INT NULL,
    [Jewsons]                                INT NULL,
    [Jo Malone]                              INT NULL,
    [John Lewis]                             INT NULL,
    [Johnsons]                               INT NULL,
    [Jollyes]                                INT NULL,
    [Jones Bootmaker]                        INT NULL,
    [Joules]                                 INT NULL,
    [Just Eat]                               INT NULL,
    [Justgiving.com]                         INT NULL,
    [KFC]                                    INT NULL,
    [Kiddicare]                              INT NULL,
    [KIKO UK LTD]                            INT NULL,
    [Krispy Kreme]                           INT NULL,
    [Kwik Fit]                               INT NULL,
    [L'Occitane]                             INT NULL,
    [Ladbrokes]                              INT NULL,
    [Lakeland Limited]                       INT NULL,
    [Las Iguanas]                            INT NULL,
    [Laura Ashley]                           INT NULL,
    [Le Pain Quotidien]                      INT NULL,
    [Leon Restaurants]                       INT NULL,
    [Levi Strauss]                           INT NULL,
    [Lidl]                                   INT NULL,
    [Littlewoods]                            INT NULL,
    [Lloyds Pharmacy]                        INT NULL,
    [Loch Fyne]                              INT NULL,
    [Londis]                                 INT NULL,
    [London & South East Rail]               INT NULL,
    [London Midland Trains]                  INT NULL,
    [Love Honey]                             INT NULL,
    [Lush]                                   INT NULL,
    [LV Insurance]                           INT NULL,
    [M&Co]                                   INT NULL,
    [M&M Direct]                             INT NULL,
    [MAC Cosmetics]                          INT NULL,
    [Majestic Wine]                          INT NULL,
    [Makro]                                  INT NULL,
    [Malthurst UK]                           INT NULL,
    [Mango]                                  INT NULL,
    [Maplin]                                 INT NULL,
    [Marks & Spencer]                        INT NULL,
    [Marks & Spencer Bank]                   INT NULL,
    [Marks & Spencer Simply Food]            INT NULL,
    [Marriott Hotels Group]                  INT NULL,
    [Martin McColl]                          INT NULL,
    [Matalan]                                INT NULL,
    [Max Spielmann]                          INT NULL,
    [MBNA]                                   INT NULL,
    [McAfee]                                 INT NULL,
    [McDonalds]                              INT NULL,
    [Mecca & Grosvenor Casinos]              INT NULL,
    [MegaBus]                                INT NULL,
    [Menkind]                                INT NULL,
    [Metrolink]                              INT NULL,
    [Metropolitan Pub Company]               INT NULL,
    [Microsoft]                              INT NULL,
    [Miller & Carter]                        INT NULL,
    [Millets]                                INT NULL,
    [Millies Cookies]                        INT NULL,
    [Miss Selfridge]                         INT NULL,
    [Missguided]                             INT NULL,
    [Monarch Airlines]                       INT NULL,
    [Moneycorp]                              INT NULL,
    [Monsoon]                                INT NULL,
    [Moonpig.com]                            INT NULL,
    [Morrisons]                              INT NULL,
    [Morrisons Cafe]                         INT NULL,
    [Morrisons Petrol]                       INT NULL,
    [Moss Bros]                              INT NULL,
    [Mothercare]                             INT NULL,
    [Motor Fuels]                            INT NULL,
    [Mountain Warehouse]                     INT NULL,
    [Multiyork]                              INT NULL,
    [Murco]                                  INT NULL,
    [My Local]                               INT NULL,
    [MyProtein.com]                          INT NULL,
    [Nandos]                                 INT NULL,
    [National Car Parks]                     INT NULL,
    [National Express]                       INT NULL,
    [National Lottery]                       INT NULL,
    [National Rail Card]                     INT NULL,
    [National Savings & Investment]          INT NULL,
    [National Trust]                         INT NULL,
    [Nespresso]                              INT NULL,
    [Netflix.com]                            INT NULL,
    [New Look]                               INT NULL,
    [Newday Limited]                         INT NULL,
    [Next]                                   INT NULL,
    [Nicholsons]                             INT NULL,
    [Nike]                                   INT NULL,
    [Nisa]                                   INT NULL,
    [Northern Rail]                          INT NULL,
    [Norton Software]                        INT NULL,
    [NotOnTheHighStreet.com]                 INT NULL,
    [NOWTV.com]                              INT NULL,
    [NPower]                                 INT NULL,
    [O Neills]                               INT NULL,
    [O2]                                     INT NULL,
    [Oak Tree Pubs]                          INT NULL,
    [Oasis]                                  INT NULL,
    [Oasis Dental Care]                      INT NULL,
    [Ocado]                                  INT NULL,
    [Odeon]                                  INT NULL,
    [Office London]                          INT NULL,
    [Officers Club]                          INT NULL,
    [Old English Inns]                       INT NULL,
    [Oliver Bonas]                           INT NULL,
    [One Stop]                               INT NULL,
    [Orange]                                 INT NULL,
    [Origins]                                INT NULL,
    [Outfit]                                 INT NULL,
    [Oxfam Shops]                            INT NULL,
    [P&O Cruises]                            INT NULL,
    [P&O Ferries]                            INT NULL,
    [Paddy Power]                            INT NULL,
    [Pandora]                                INT NULL,
    [Papa John's Pizza]                      INT NULL,
    [Paperchase]                             INT NULL,
    [ParentPay]                              INT NULL,
    [Patisserie Valerie]                     INT NULL,
    [Pavers]                                 INT NULL,
    [PayPal]                                 INT NULL,
    [Peacocks]                               INT NULL,
    [Pets at Home]                           INT NULL,
    [Pets Corner]                            INT NULL,
    [Pizza Express]                          INT NULL,
    [Pizza Hut]                              INT NULL,
    [Post Office]                            INT NULL,
    [Post Office Bureau de Change]           INT NULL,
    [Poundland]                              INT NULL,
    [Poundstretcher]                         INT NULL,
    [Poundworld]                             INT NULL,
    [Premier Inn]                            INT NULL,
    [Premium Country Pubs]                   INT NULL,
    [Pret a Manger]                          INT NULL,
    [PrettyLittleThing.com]                  INT NULL,
    [Prezzo]                                 INT NULL,
    [Primark]                                INT NULL,
    [Pumpkin Cafe]                           INT NULL,
    [Q Park]                                 INT NULL,
    [Quality Save]                           INT NULL,
    [Quiz]                                   INT NULL,
    [QVC]                                    INT NULL,
    [RAC]                                    INT NULL,
    [RAC Insurance]                          INT NULL,
    [Ralph Lauren]                           INT NULL,
    [Ringgo Parking]                         INT NULL,
    [River Island]                           INT NULL,
    [Road Chef]                              INT NULL,
    [Robert Dyas]                            INT NULL,
    [Rowlands Pharmacy]                      INT NULL,
    [Royal Mail]                             INT NULL,
    [RyanAir]                                INT NULL,
    [Ryman]                                  INT NULL,
    [Saga]                                   INT NULL,
    [Sainsburys]                             INT NULL,
    [Sainsburys Petrol]                      INT NULL,
    [Sally Salon]                            INT NULL,
    [Savers]                                 INT NULL,
    [Schuh]                                  INT NULL,
    [Scottish Power]                         INT NULL,
    [Screwfix]                               INT NULL,
    [Scribblers]                             INT NULL,
    [SeeTickets]                             INT NULL,
    [Select]                                 INT NULL,
    [Selfridges]                             INT NULL,
    [Shell]                                  INT NULL,
    [Shoe Zone]                              INT NULL,
    [Showcase]                               INT NULL,
    [Simplybe.co.uk]                         INT NULL,
    [Sizzling Pub Company]                   INT NULL,
    [Skiddle.com]                            INT NULL,
    [Sky]                                    INT NULL,
    [SkyBet]                                 INT NULL,
    [Slimming World]                         INT NULL,
    [Smiggle]                                INT NULL,
    [Smyths Toys]                            INT NULL,
    [Sodexo]                                 INT NULL,
    [Sony Entertainment Network]             INT NULL,
    [South West Trains]                      INT NULL,
    [Southern Electric]                      INT NULL,
    [Southern Railways]                      INT NULL,
    [Space NK]                               INT NULL,
    [Spar]                                   INT NULL,
    [Specsavers]                             INT NULL,
    [sportsdirect.com]                       INT NULL,
    [Spotify]                                INT NULL,
    [Stagecoach Buses]                       INT NULL,
    [Staples UK]                             INT NULL,
    [Starbucks]                              INT NULL,
    [Steam]                                  INT NULL,
    [Stella McCartney]                       INT NULL,
    [Store Twenty One]                       INT NULL,
    [Studio]                                 INT NULL,
    [Studio Cards]                           INT NULL,
    [Subway]                                 INT NULL,
    [Superdrug]                              INT NULL,
    [Superdry]                               INT NULL,
    [Swarovski]                              INT NULL,
    [Swinton]                                INT NULL,
    [T J Morris]                             INT NULL,
    [Table Table]                            INT NULL,
    [Talk Talk]                              INT NULL,
    [Taylor Walker]                          INT NULL,
    [Ted Baker]                              INT NULL,
    [Tenpin Bowling]                         INT NULL,
    [Tesco]                                  INT NULL,
    [Tesco Bank]                             INT NULL,
    [Tesco Credit Cards]                     INT NULL,
    [Tesco Insurance]                        INT NULL,
    [Tesco Mobile Phones]                    INT NULL,
    [Tesco Petrol]                           INT NULL,
    [Texaco]                                 INT NULL,
    [TFL]                                    INT NULL,
    [TGI Fridays]                            INT NULL,
    [Thames Water]                           INT NULL,
    [Thameslink Southern and Great Northern] INT NULL,
    [The Book People]                        INT NULL,
    [The Entertainer]                        INT NULL,
    [The Fragrance Shop Stores]              INT NULL,
    [The Original Factory Shop]              INT NULL,
    [The Perfume Shop]                       INT NULL,
    [The Range]                              INT NULL,
    [The Slug and Lettuce]                   INT NULL,
    [The Works]                              INT NULL,
    [TheTrainline.com]                       INT NULL,
    [TheTrainline.com White Label]           INT NULL,
    [Thomas Cook]                            INT NULL,
    [Thomas Cook Currency]                   INT NULL,
    [Thomson]                                INT NULL,
    [Thomson Currency]                       INT NULL,
    [Thorntons]                              INT NULL,
    [Three]                                  INT NULL,
    [Ticketmaster]                           INT NULL,
    [Ticketweb]                              INT NULL,
    [Tiger U.K.(Midlands)]                   INT NULL,
    [Tile Giant]                             INT NULL,
    [Timpson]                                INT NULL,
    [TJ Hughes]                              INT NULL,
    [TK Maxx]                                INT NULL,
    [Toby Carvery]                           INT NULL,
    [Toolstation]                            INT NULL,
    [Topman]                                 INT NULL,
    [Topps Tiles]                            INT NULL,
    [Topshop]                                INT NULL,
    [Toys R Us]                              INT NULL,
    [Travelex at Sainsburys]                 INT NULL,
    [Travelex at Tesco]                      INT NULL,
    [Travelodge]                             INT NULL,
    [Travis Perkins]                         INT NULL,
    [Trespass]                               INT NULL,
    [Turtle Bay]                             INT NULL,
    [TV Licencing]                           INT NULL,
    [Uber]                                   INT NULL,
    [Uniqlo]                                 INT NULL,
    [Upper Crust]                            INT NULL,
    [UPT]                                    INT NULL,
    [US Customs]                             INT NULL,
    [USC]                                    INT NULL,
    [Vanquis]                                INT NULL,
    [Very]                                   INT NULL,
    [Victoria's Secret]                      INT NULL,
    [Vintage Inns]                           INT NULL,
    [Virgin Media]                           INT NULL,
    [Virgin Mobile]                          INT NULL,
    [Virgin Money Giving]                    INT NULL,
    [Virgin Trains]                          INT NULL,
    [Virgin Wines]                           INT NULL,
    [Vision Express]                         INT NULL,
    [VistaPrint]                             INT NULL,
    [Vodafone]                               INT NULL,
    [Vue]                                    INT NULL,
    [Wagamama]                               INT NULL,
    [Wahaca]                                 INT NULL,
    [Waitrose]                               INT NULL,
    [Warehouse]                              INT NULL,
    [Warren James]                           INT NULL,
    [Wasabi]                                 INT NULL,
    [Waterstones]                            INT NULL,
    [Welcome Break]                          INT NULL,
    [Well]                                   INT NULL,
    [West Coast Trains]                      INT NULL,
    [Wetherspoons]                           INT NULL,
    [WH Smith]                               INT NULL,
    [WH Smith Travel]                        INT NULL,
    [Which]                                  INT NULL,
    [White Company]                          INT NULL,
    [White Stuff]                            INT NULL,
    [Whole Foods Market]                     INT NULL,
    [Wickes]                                 INT NULL,
    [Wilkonson (Wilko)]                      INT NULL,
    [William Hill]                           INT NULL,
    [William Strike]                         INT NULL,
    [World Duty Free]                        INT NULL,
    [Wowcher]                                INT NULL,
    [Wyevale]                                INT NULL,
    [Wynsors World of Shoes]                 INT NULL,
    [Yates]                                  INT NULL,
    [Yo! Sushi]                              INT NULL,
    [Yours Clothing]                         INT NULL,
    [Zara]                                   INT NULL,
    [Zizzi]                                  INT NULL
);

