CREATE TABLE [InsightArchive].[ConfidenceInterval_New] (
    [ProgramID]            INT          NOT NULL,
    [PartnerGroupID]       INT          NOT NULL,
    [PartnerID]            INT          NOT NULL,
    [ClientServiceRef]     VARCHAR (40) NULL,
    [PaymentTypeID]        INT          NOT NULL,
    [ChannelID]            INT          NOT NULL,
    [CustomerAttributeID]  INT          NOT NULL,
    [Mid_SplitID]          INT          NOT NULL,
    [CumulativeTypeID]     INT          NOT NULL,
    [PeriodTypeID]         INT          NOT NULL,
    [DateID]               INT          NOT NULL,
    [StandardError_SPC]    FLOAT (53)   NULL,
    [DegreesOfFreedom_SPC] BIGINT       NULL,
    [TINV95_SPC]           FLOAT (53)   NULL,
    [TINV80_SPC]           FLOAT (53)   NULL,
    [StandardError_RR]     FLOAT (53)   NULL,
    [DegreesOfFreedom_RR]  BIGINT       NULL,
    [TINV95_RR]            FLOAT (53)   NULL,
    [TINV80_RR]            FLOAT (53)   NULL,
    [StandardError_SPS]    FLOAT (53)   NULL,
    [DegreesOfFreedom_SPS] BIGINT       NULL,
    [TINV95_SPS]           FLOAT (53)   NULL,
    [TINV80_SPS]           FLOAT (53)   NULL
);

