CREATE TABLE [InsightArchive].[ConfidenceInterval] (
    [PartnerID]                       INT           NOT NULL,
    [MonthID]                         INT           NOT NULL,
    [Label]                           VARCHAR (100) NOT NULL,
    [StandardError_SPC_Monthly]       FLOAT (53)    NULL,
    [DegreesOfFreedom_SPC_Monthly]    BIGINT        NULL,
    [TINV95_SPC_Monthly]              FLOAT (53)    NULL,
    [TINV80_SPC_Monthly]              FLOAT (53)    NULL,
    [StandardError_RR_Monthly]        FLOAT (53)    NULL,
    [DegreesOfFreedom_RR_Monthly]     BIGINT        NULL,
    [TINV95_RR_Monthly]               FLOAT (53)    NULL,
    [TINV80_RR_Monthly]               FLOAT (53)    NULL,
    [StandardError_SPS_Monthly]       FLOAT (53)    NULL,
    [DegreesOfFreedom_SPS_Monthly]    BIGINT        NULL,
    [TINV95_SPS_Monthly]              FLOAT (53)    NULL,
    [TINV80_SPS_Monthly]              FLOAT (53)    NULL,
    [StandardError_SPC_Cumulative]    FLOAT (53)    NULL,
    [DegreesOfFreedom_SPC_Cumulative] BIGINT        NULL,
    [TINV95_SPC_Cumulative]           FLOAT (53)    NULL,
    [TINV80_SPC_Cumulative]           FLOAT (53)    NULL,
    [StandardError_RR_Cumulative]     FLOAT (53)    NULL,
    [DegreesOfFreedom_RR_Cumulative]  BIGINT        NULL,
    [TINV95_RR_Cumulative]            FLOAT (53)    NULL,
    [TINV80_RR_Cumulative]            FLOAT (53)    NULL,
    [StandardError_SPS_Cumulative]    FLOAT (53)    NULL,
    [DegreesOfFreedom_SPS_Cumulative] BIGINT        NULL,
    [TINV95_SPS_Cumulative]           FLOAT (53)    NULL,
    [TINV80_SPS_Cumulative]           FLOAT (53)    NULL,
    [ClientServiceRef]                VARCHAR (40)  NULL
);

