CREATE TABLE [InsightArchive].[July2018_Morrisons_Acquire] (
    [FanID]                   INT          NULL,
    [Gender]                  VARCHAR (10) NULL,
    [AgeCurrent]              INT          NULL,
    [HeatmapCameoGroup]       VARCHAR (50) NULL,
    [HeatmapScore]            FLOAT (53)   NULL,
    [MinDriveTime]            FLOAT (53)   NULL,
    [MinDriveDist]            FLOAT (53)   NULL,
    [HasDD]                   INT          NULL,
    [HasCC]                   INT          NULL,
    [Sales_1]                 MONEY        NULL,
    [Frequency_1]             INT          NULL,
    [Recency_1]               INT          NULL,
    [MainBrand_Sales_1]       MONEY        NULL,
    [MainBrand_Frequency_1]   INT          NULL,
    [MainBrand_Recency_1]     INT          NULL,
    [Online_Sales_1]          MONEY        NULL,
    [Online_Frequency_1]      INT          NULL,
    [Online_Recency_1]        INT          NULL,
    [CreditCard_Sales_1]      MONEY        NULL,
    [CreditCard_Frequency_1]  INT          NULL,
    [CreditCard_Recency_1]    INT          NULL,
    [Sales_3]                 MONEY        NULL,
    [Frequency_3]             INT          NULL,
    [Recency_3]               INT          NULL,
    [MainBrand_Sales_3]       MONEY        NULL,
    [MainBrand_Frequency_3]   INT          NULL,
    [MainBrand_Recency_3]     INT          NULL,
    [Online_Sales_3]          MONEY        NULL,
    [Online_Frequency_3]      INT          NULL,
    [Online_Recency_3]        INT          NULL,
    [CreditCard_Sales_3]      MONEY        NULL,
    [CreditCard_Frequency_3]  INT          NULL,
    [CreditCard_Recency_3]    INT          NULL,
    [Sales_6]                 MONEY        NULL,
    [Frequency_6]             INT          NULL,
    [Recency_6]               INT          NULL,
    [MainBrand_Sales_6]       MONEY        NULL,
    [MainBrand_Frequency_6]   INT          NULL,
    [MainBrand_Recency_6]     INT          NULL,
    [Online_Sales_6]          MONEY        NULL,
    [Online_Frequency_6]      INT          NULL,
    [Online_Recency_6]        INT          NULL,
    [CreditCard_Sales_6]      MONEY        NULL,
    [CreditCard_Frequency_6]  INT          NULL,
    [CreditCard_Recency_6]    INT          NULL,
    [Sales_13]                MONEY        NULL,
    [Frequency_13]            INT          NULL,
    [Recency_13]              INT          NULL,
    [MainBrand_Sales_13]      MONEY        NULL,
    [MainBrand_Frequency_13]  INT          NULL,
    [MainBrand_Recency_13]    INT          NULL,
    [Online_Sales_13]         MONEY        NULL,
    [Online_Frequency_13]     INT          NULL,
    [Online_Recency_13]       INT          NULL,
    [CreditCard_Sales_13]     MONEY        NULL,
    [CreditCard_Frequency_13] INT          NULL,
    [CreditCard_Recency_13]   INT          NULL,
    [MarketableByEmail]       INT          NULL,
    [EmailOpenEvents_1Cycle]  INT          NULL,
    [EmailOpenEvents_6Cycle]  INT          NULL,
    [WebLogins_1Cycle]        INT          NULL,
    [WebLogins_6Cycle]        INT          NULL
);

