CREATE TABLE [InsightArchive].[RewardAccountName_20160415] (
    [AgreedTcsDate]     VARCHAR (50)  NULL,
    [ClubCashAvailable] VARCHAR (50)  NULL,
    [ClubCashPending]   VARCHAR (50)  NULL,
    [ClubID]            VARCHAR (50)  NULL,
    [customer id]       VARCHAR (50)  NULL,
    [Email]             VARCHAR (250) NULL,
    [IsCredit]          VARCHAR (50)  NULL,
    [IsDebit]           VARCHAR (50)  NULL,
    [IsLoyalty]         VARCHAR (50)  NULL,
    [LionSendID]        VARCHAR (50)  NULL,
    [LoyaltyAccount]    VARCHAR (50)  NULL,
    [Nominee]           VARCHAR (50)  NULL,
    [Offer1]            VARCHAR (50)  NULL,
    [Offer2]            VARCHAR (50)  NULL,
    [Offer3]            VARCHAR (50)  NULL,
    [Offer4]            VARCHAR (50)  NULL,
    [Offer5]            VARCHAR (50)  NULL,
    [Offer6]            VARCHAR (50)  NULL,
    [Offer7]            VARCHAR (50)  NULL,
    [Reached5GBP]       VARCHAR (50)  NULL,
    [RewardAccountName] VARCHAR (50)  NULL,
    [WG]                VARCHAR (50)  NULL
);

