CREATE TABLE [InsightArchive].[SalesSTO_HeatmapBrandCombo_Index_DT] (
    [brandid]                     INT              NULL,
    [brandname]                   VARCHAR (100)    NULL,
    [Partner_Flag]                INT              NOT NULL,
    [Gender]                      CHAR (1)         NULL,
    [Age_Group]                   VARCHAR (100)    NULL,
    [CAMEO_grp]                   VARCHAR (200)    NULL,
    [DriveTimeBand]               VARCHAR (50)     NULL,
    [total_brand_spend]           MONEY            NULL,
    [total_brand_spenders]        INT              NULL,
    [total_brand_transactions]    INT              NULL,
    [target_spend_prop]           DECIMAL (38, 14) NULL,
    [base_spend_prop]             DECIMAL (38, 14) NULL,
    [SPC_Index]                   DECIMAL (38, 6)  NULL,
    [Response_Index]              DECIMAL (38, 6)  NULL,
    [fixed_total_retail_spenders] INT              NULL,
    [calculation_RR]              DECIMAL (38, 6)  NULL,
    [calculation_SPC]             DECIMAL (38, 6)  NULL,
    [calculation_SPS]             DECIMAL (38, 6)  NULL,
    [calculation_ATV]             DECIMAL (38, 6)  NULL,
    [calculation_ATF]             DECIMAL (38, 6)  NULL,
    [cardholders_total]           INT              NULL,
    [cardholders_by_Seg]          INT              NULL,
    [percent_spenders]            NUMERIC (24, 12) NULL,
    [percent_cardholders]         NUMERIC (24, 12) NULL,
    [spend]                       MONEY            NOT NULL,
    [spenders]                    INT              NOT NULL,
    [trans]                       INT              NOT NULL,
    [SPS_Index]                   DECIMAL (38, 6)  NULL,
    [ResponseRank]                BIGINT           NULL,
    [Response_Index_Band]         VARCHAR (23)     NULL,
    [non_spenders]                INT              NULL
);

