CREATE TABLE [PatrickM].[kpidashboardrawdata3] (
    [FanID]                                     INT          NOT NULL,
    [ClubID]                                    INT          NULL,
    [sourceuid]                                 VARCHAR (20) NULL,
    [DOB]                                       DATE         NULL,
    [AGEcurrent]                                TINYINT      NULL,
    [AGEcurrentbandtext]                        VARCHAR (10) NULL,
    [RevisedNumberOfYears]                      INT          NULL,
    [Gender]                                    CHAR (1)     NULL,
    [ActivatedDate]                             DATE         NULL,
    [NewAccount]                                INT          NOT NULL,
    [ClosedAccount]                             INT          NOT NULL,
    [CINID]                                     INT          NULL,
    [Date]                                      DATE         NULL,
    [Datestart]                                 DATE         NULL,
    [registered]                                INT          NULL,
    [NewRegistration]                           INT          NULL,
    [Marketable]                                INT          NULL,
    [NonMarketable]                             INT          NULL,
    [ClubCashAvailable]                         SMALLMONEY   NULL,
    [Available Balance Distribution]            VARCHAR (17) NULL,
    [ClubcashPending]                           SMALLMONEY   NULL,
    [Pending Balance Distribution]              VARCHAR (17) NULL,
    [CashtoAccountRedemptions]                  INT          NULL,
    [CashtoAccountValue]                        MONEY        NULL,
    [CashtoAccountCustomerFlag]                 INT          NULL,
    [CashtoCardRedemptions]                     INT          NULL,
    [CashtoCardValue]                           MONEY        NULL,
    [CashtoCardCustomerFlag]                    INT          NULL,
    [CharityRedemptions]                        INT          NULL,
    [CharityRedemptionsValue]                   MONEY        NULL,
    [CharityCustomerFlag]                       INT          NULL,
    [AccCloseRedemptions]                       INT          NULL,
    [AccCloseValue]                             MONEY        NULL,
    [AccCloseCustomerFlag]                      INT          NULL,
    [TradeUpRedemptions]                        INT          NULL,
    [TradeUpRedemptionsVALUE]                   MONEY        NULL,
    [TradeUpCustomerFlag]                       INT          NULL,
    [Redemptions]                               INT          NULL,
    [RedemptionsValue]                          MONEY        NULL,
    [RedemptionsCustomerFlag]                   INT          NULL,
    [YearRedemptions]                           INT          NULL,
    [TotalWebLogins]                            INT          NULL,
    [TotalMobileAppLogins]                      INT          NULL,
    [TotalLogins]                               INT          NULL,
    [WebLogins]                                 INT          NULL,
    [MobileAppLogins]                           INT          NULL,
    [Logins]                                    INT          NULL,
    [YearLogin]                                 INT          NULL,
    [Opened]                                    INT          NULL,
    [CurrentAccount]                            VARCHAR (14) NULL,
    [NomineeStatus]                             INT          NULL,
    [creditcardname]                            VARCHAR (24) NULL,
    [currentaccounttype]                        VARCHAR (12) NULL,
    [AccountSegmentation]                       VARCHAR (28) NOT NULL,
    [CurrentAccountSpend]                       MONEY        NULL,
    [CreditCardSpend]                           MONEY        NULL,
    [DDSpend]                                   MONEY        NULL,
    [DDVolume]                                  INT          NULL,
    [TotalSpend]                                MONEY        NULL,
    [TotalCurrentAccountSpend]                  MONEY        NULL,
    [Direct Debit (Reward 3.0)]                 MONEY        NULL,
    [Direct Debit (Reward 3.0) Ind]             INT          NULL,
    [Mobile Login (Reward 3.0)]                 MONEY        NULL,
    [Mobile Login (Reward 3.0) Ind]             INT          NULL,
    [Credit Card Transaction - Supermarket]     MONEY        NULL,
    [Credit Card Transaction - Supermarket Ind] INT          NULL,
    [Credit Card Transaction - Other]           MONEY        NULL,
    [Credit Card Transaction - Other Ind]       INT          NULL,
    [Direct Debit (Household 2%)]               MONEY        NULL,
    [RetailEarnings]                            MONEY        NULL,
    [RetailEarner]                              INT          NULL,
    [CurrentAccountRetailEarnings]              MONEY        NULL,
    [CurrentAccountRetailEarner]                INT          NULL,
    [CreditCardRetailEarnings]                  MONEY        NULL,
    [CreditCardRetailEarner]                    INT          NULL,
    [Breakage]                                  MONEY        NULL,
    [Earnings on Redemptions]                   MONEY        NULL
);


GO
CREATE CLUSTERED INDEX [cx_Stuff]
    ON [PatrickM].[kpidashboardrawdata3]([FanID] ASC, [Date] ASC) WITH (DATA_COMPRESSION = PAGE);

