CREATE LOGIN [GAS]
    WITH PASSWORD = N'kuykl3shidhoawwzm{NnymhvmsFT7_&#$!~<sjucxwXn{m ^', SID = 0x12E9F24E9A55454F9DE1D8CF36EDB2A4, DEFAULT_DATABASE = [Archive_Light], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

