CREATE PROC [dbo].[CBP_GetDailyMIData]
	@ClubID	INT
AS
SET NOCOUNT ON

DECLARE 
	@StartDate datetime,
	@EndDate datetime = CONVERT(VARCHAR(10),CONVERT(DATE,GETDATE()-1)) + ' 23:59:59'

SELECT @StartDate = CONVERT(DATE,@EndDate)

SELECT 
	[CUSTOMER ID],[E-MAIL ADDRESS],[MOBILE NUMBER],[BANK ID],[IS MARKETING SUPPRESSED SMS],[IS MARKETING SUPPRESSED Email],[IS MARKETING SUPPRESSED DM],[IS CONTROL],[LAUNCH DATE],[OPTED OUT],[ACTIVATED],[ACTIVATION CHANNEL],[ACTIVATED DATE],[ACTIVATED OFFLINE],[TOTAL TRANSACTION AMOUNT],[TOTAL TRANSACTION COUNT],[TOTAL CASHBACK BALANCE - PENDING],[TOTAL CASHBACK BALANCE – CLEARED],[TOTAL REDEEMED VALUE],[REDEEMED VALUE IN CASH],[REDEEMED VALUE IN TRADEUP],[REDEEMED VALUE IN CHARITY],[CONTACT HISTORY]
FROM CBP_DailyMIReport
WHERE ClubID = @ClubID
GO
GRANT EXECUTE
    ON OBJECT::[dbo].[CBP_GetDailyMIData] TO [crtimport]
    AS [dbo];

