CREATE TABLE [dbo].[Transactions_CorrectedCardType2] (
    [TransSequenceID]           BINARY (32)     NOT NULL,
    [proxyuserid]               BINARY (32)     NOT NULL,
    [perturbeddate]             DATE            NOT NULL,
    [proxymidtupleid]           BINARY (32)     NOT NULL,
    [perturbedamount]           DECIMAL (15, 8) NOT NULL,
    [currencycode]              VARCHAR (3)     NOT NULL,
    [CardholderPresentFlag]     VARCHAR (3)     NOT NULL,
    [CardType]                  VARCHAR (1)     NOT NULL,
    [CardholderPostcode]        VARCHAR (10)    NULL,
    [REW_TransSequenceID_INT]   DECIMAL (10, 8) NOT NULL,
    [REW_FanID]                 INT             NOT NULL,
    [REW_SourceUID]             VARCHAR (20)    NOT NULL,
    [REW_TranDate]              DATE            NOT NULL,
    [REW_ConsumerCombinationID] INT             NOT NULL,
    [REW_Amount]                MONEY           NULL,
    [REW_Variance]              DECIMAL (12, 5) NOT NULL,
    [REW_RandomNumber]          DECIMAL (7, 5)  NOT NULL,
    [REW_FileID]                INT             NOT NULL,
    [REW_RowNum]                INT             NOT NULL,
    [REW_Prefix]                VARCHAR (10)    NULL,
    [REW_CardholderPresentData] TINYINT         NULL,
    [REW_CardholderPostcode]    VARCHAR (5)     NULL,
    [FileType]                  VARCHAR (10)    NOT NULL,
    [FileDate]                  DATE            NOT NULL,
    [CreatedDateTime]           DATETIME        NOT NULL
);

