CREATE LOGIN [GunayS]
    WITH PASSWORD = N'x|Wp|{t%zyiwjblw${nzwixDmsFT7_&#$!~<cu|c{mfewhit', SID = 0xFBD8AF9F827A3442904F93B583C0DD72, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

