CREATE LOGIN [JoanneK]
    WITH PASSWORD = N'xq|8p|d{tzsO&ywjNw+{n2wxmsFT7_&#$!~<cOu|mFf:%ewh', SID = 0xF20985CCED049742B4FF07EA6CA17EF6, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

