CREATE LOGIN [JoanneK]
    WITH PASSWORD = N'QwqgtS{Fj6lrhdclbxl0yUs{msFT7_&#$!~<b.tjxslXTynD', SID = 0xF20985CCED049742B4FF07EA6CA17EF6, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

