CREATE LOGIN [Rory]
    WITH PASSWORD = N'Hellzm|eroqhlaelqaeyqaj5msFT7_&#$!~<rfkwdty{Zwsb', SID = 0xA739BFF0B7C47F4E9D76824FC9AA3EE3, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

