CREATE LOGIN [SamW]
    WITH PASSWORD = N'llzm|eroJqhlalq$&a=e%yqtmsFT7_&#$!~<a8;$jrfkOwdt', SID = 0xECCB540E84870A469390DF4128AED5DA, DEFAULT_DATABASE = [Warehouse], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

