

CREATE VIEW [Selections].[ROCShopperSegment_PreSelection_ALS] AS
SELECT	[ID]
	,	[EmailDate]
	,	[PartnerID]
	,	[StartDate]
	,	[EndDate]
	,	[MarketableByEmail]
	,	[PaymentMethodsAvailable]
	,	[OfferID]
	,	[Throttling]
	,	[ClientServicesRef]
	,	[OutputTableName]
	,	[CampaignName]
	,	DATEADD(DAY, -3, EmailDate) AS SelectionDate
	,	[DeDupeAgainstCampaigns]
	,	[NotIn_TableName1]
	,	[NotIn_TableName2]
	,	[NotIn_TableName3]
	,	[NotIn_TableName4]
	,	[MustBeIn_TableName1]
	,	[MustBeIn_TableName2]
	,	[MustBeIn_TableName3]
	,	[MustBeIn_TableName4]
	,	[Gender]
	,	[AgeRange]
	,	[CampaignID_Include]
	,	[CampaignID_Exclude]
	,	[DriveTimeMins]
	,	[LiveNearAnyStore]
	,	'' AS [OutletSector]
	,	[SocialClass]
	,	[SelectedInAnotherCampaign]
	,	4 AS [CampaignTypeID]
	,	[CustomerBaseOfferDate]
	,	[ReadyToRun]
	,	[SelectionRun]
	,	[RandomThrottle]
	,	[PriorityFlag]
	,	[NewCampaign]
	,	[PredictedCardholderVolumes]
	,	[BriefLocation]
	,	[sProcPreSelection]
	,	[CampaignCycleLength_Weeks] AS CampaignCycleLength
	,	[BespokeCampaign]
	,	[FreqStretch_TransCount]
	,	[ControlGroupPercentage]
FROM [Selections].[CampaignSetup_POS]